#!/usr/bin/env python3
"""Run Case #3/#4 with the force-calibrated t=0 initial mesh.

These are the two raw Pitois Fig. 5 separation runs that replace the old
r1.205 mm sensitivity runs.  The initial mesh is the ddgclib/FHeron-evaluated
t=0 force-calibrated mesh generated by
``Case_2b_initialmesh_t0_force_calibrated.py``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parent
SOLVER = ROOT / "v5Conti_vd_Dimentionless_VolFlux0_speed_FHeron_cu0_ddgclib.py"
MESH_SCRIPT = ROOT / "Case_2b_initialmesh_t0_force_calibrated.py"
INITIAL_MESH_DIR = ROOT / "out" / "Case_2b_initialmesh_t0_force_calibrated"
INITIAL_MESH = INITIAL_MESH_DIR / "mesh_initial.msh"
INITIAL_MESH_SUMMARY = INITIAL_MESH_DIR / "summary.json"
EXPECTED_FORCE_MN = 1.515311539463195
EXPECTED_VOLUME_UL = 1.10
REJECTED_EQ6_RCL_MM = 1.2074


CASE_SPECS = {
    "3": {
        "name": "v5Conti_vd_Dimentionless_VolFlux0_speed_FHeron_cu0_ddgclib_case3",
        "closure": "compressible",
        "extra_args": (
            "--gmsh-contact-angle-kinematics",
            "--compressible-incompressible-limit-projection",
            "--allow-contact-line-growth",
            "--solver-viscous-force-model",
            "edge_flux",
            "--no-solver-pr33-pressure-force",
            "--no-solver-hydrostatic-force",
            "--no-raw-mesh-png",
        ),
    },
    "4": {
        "name": "v5Conti_vd_Dimentionless_VolFlux0_speed_FHeron_cu0_ddgclib_case4",
        "closure": "incompressible",
        # The incompressible PR#33 projection is physically active, but a small
        # Tikhonov regularization suppresses projection chatter without changing
        # the raw ddgclib/FHeron gorge-force reporting path.
        "extra_args": ("--incompressible-projection-regularization", "1e-6"),
    },
}


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _generate_initial_mesh() -> None:
    if not MESH_SCRIPT.is_file():
        raise FileNotFoundError(f"Calibrated mesh generator is missing: {MESH_SCRIPT}")
    cmd = [sys.executable, str(MESH_SCRIPT), "--out-dir", str(INITIAL_MESH_DIR)]
    print(f"[mesh] {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=ROOT, check=True)


def _load_initial_mesh_summary() -> dict:
    if not INITIAL_MESH_SUMMARY.is_file():
        raise FileNotFoundError(f"Calibrated mesh summary is missing: {INITIAL_MESH_SUMMARY}")
    return json.loads(INITIAL_MESH_SUMMARY.read_text(encoding="utf-8"))


def _validate_initial_mesh() -> dict:
    if not INITIAL_MESH.is_file():
        raise FileNotFoundError(f"Calibrated initial mesh is missing: {INITIAL_MESH}")
    summary = _load_initial_mesh_summary()
    chosen = summary.get("chosen", {})
    rcl_mm = float(chosen.get("rcl_mm", "nan"))
    force_mn = float(chosen.get("force_mn", "nan"))
    volume_ul = float(chosen.get("actual_volume_ul", "nan"))
    force_model = str(summary.get("force_model", ""))

    if abs(rcl_mm - REJECTED_EQ6_RCL_MM) < 0.02:
        raise RuntimeError(
            f"Refusing Eq.6/r1.205-style mesh for #3/#4: summary r_cl={rcl_mm:.9f} mm"
        )
    if abs(force_mn - EXPECTED_FORCE_MN) > 1.0e-6:
        raise RuntimeError(
            f"Calibrated mesh does not match the first Fig. 5 force point: "
            f"{force_mn:.9f} mN vs {EXPECTED_FORCE_MN:.9f} mN"
        )
    if abs(volume_ul - EXPECTED_VOLUME_UL) > 1.0e-6:
        raise RuntimeError(
            f"Calibrated mesh volume is not Case 2b volume: {volume_ul:.9f} uL"
        )
    if "ddgclib/FHeron" not in force_model:
        raise RuntimeError(f"Calibrated mesh summary is not from the ddgclib/FHeron path: {force_model}")

    mesh_hash = _sha256(INITIAL_MESH)
    print(
        "[mesh] using force-calibrated mesh: "
        f"r_cl={rcl_mm:.9f} mm, "
        f"neck={float(chosen.get('neck_radius_mm', float('nan'))):.9f} mm, "
        f"D/R={float(chosen.get('d_over_r', float('nan'))):.12f}, "
        f"V={volume_ul:.9f} uL, "
        f"|F|={force_mn:.9f} mN",
        flush=True,
    )
    print(f"[mesh] sha256={mesh_hash}", flush=True)
    print(f"[mesh] path={INITIAL_MESH}", flush=True)
    return summary


def _run_case(
    case_id: str,
    *,
    steps: int,
    record_every: int,
    mesh_snapshot_every: int,
    history_png_every: int,
    quiet_solver: bool,
) -> None:
    spec = CASE_SPECS[case_id]
    out_dir = ROOT / spec["name"]
    cmd = [
        sys.executable,
        str(SOLVER),
        "--steps",
        str(int(steps)),
        "--closure",
        str(spec["closure"]),
        "--initial-msh-path",
        str(INITIAL_MESH),
        "--initial-contact-radius-mode",
        "loaded",
        "--no-cox-contact-line-force",
        "--gorge-pressure-model",
        "axisym_fit",
        "--fheron-neck-pressure-factor",
        "1.0",
        "--record-every",
        str(int(record_every)),
        "--mesh-snapshot-every",
        str(int(mesh_snapshot_every)),
        "--history-png-every",
        str(int(history_png_every)),
        "--out-dir",
        str(out_dir),
    ]
    cmd.extend(str(arg) for arg in spec.get("extra_args", ()))
    if quiet_solver:
        cmd.append("--quiet")
    print(f"[case {case_id}] {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=ROOT, check=True)

    history_path = out_dir / "separation_history.json"
    if history_path.is_file():
        payload = json.loads(history_path.read_text(encoding="utf-8"))
        history = payload.get("history", [])
        first = history[0] if history else {}
        last = history[-1] if history else {}
        print(
            f"[case {case_id}] wrote {len(history)} rows, "
            f"step {first.get('step')} -> {last.get('step')}, "
            f"force_model={first.get('force_model')}",
            flush=True,
        )
        print(
            f"[case {case_id}] initial_msh_path={payload.get('config', {}).get('initial_msh_path')}",
            flush=True,
        )
        print(
            f"[case {case_id}] first |F|={abs(float(first.get('fixed_force_axial', 0.0))) * 1.0e3:.9f} mN, "
            f"last |F|={abs(float(last.get('fixed_force_axial', 0.0))) * 1.0e3:.9f} mN",
            flush=True,
        )
        print(
            f"[case {case_id}] compare_png={out_dir / '1_pitois2000_volumetric_separation_digitized_compare.png'}",
            flush=True,
        )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", choices=("3", "4", "both"), default="both")
    parser.add_argument("--steps", type=int, default=5000)
    parser.add_argument("--record-every", type=int, default=1)
    parser.add_argument("--mesh-snapshot-every", type=int, default=0)
    parser.add_argument("--history-png-every", type=int, default=0)
    parser.add_argument("--regenerate-mesh", action="store_true")
    parser.add_argument("--verbose-solver", action="store_true")
    args = parser.parse_args(argv)

    if args.regenerate_mesh or not INITIAL_MESH.is_file() or not INITIAL_MESH_SUMMARY.is_file():
        _generate_initial_mesh()
    _validate_initial_mesh()
    if not SOLVER.is_file():
        raise FileNotFoundError(f"Solver is missing: {SOLVER}")

    cases = ("3", "4") if args.case == "both" else (args.case,)
    for case_id in cases:
        _run_case(
            case_id,
            steps=int(args.steps),
            record_every=int(args.record_every),
            mesh_snapshot_every=int(args.mesh_snapshot_every),
            history_png_every=int(args.history_png_every),
            quiet_solver=not bool(args.verbose_solver),
        )


if __name__ == "__main__":
    main()
