#!/usr/bin/env python3
"""Create a PPT-cover GIF for an approach-case run.

The cover stacks the oblique mesh animation above a compact Fig. 6 force
chart with explicit x/y axis labels.  It expects the one-window diagnostic
frames generated by ``Approach/1window_gif.py``.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
DEFAULT_RUN_DIR = ROOT / "case_5_finial"
DEFAULT_FRAME_DIR_NAME = "case5_1window_frames"
DEFAULT_OUTPUT_NAME = "case5_approach_cover_mesh_top20_force_bottom_xlabel.gif"
DEFAULT_FIRST_NAME = "case5_approach_cover_mesh_top20_force_bottom_xlabel_first.png"

FRAME_RE = re.compile(r"diagnostic_step(?P<step>\d+)\.png$")

APPROACH_START_D_OVER_R = 0.20
PARTICLE_RADIUS_M = 4.0e-3
GAP_RATE_MPS = 10.0e-6

EXP_D_OVER_R = np.array(
    [
        0.200,
        0.190,
        0.180,
        0.170,
        0.160,
        0.150,
        0.140,
        0.130,
        0.120,
        0.110,
        0.100,
        0.090,
        0.080,
        0.070,
        0.060,
        0.050,
        0.045,
        0.040,
        0.035,
        0.030,
        0.027,
        0.024,
        0.021,
        0.018,
    ],
    dtype=float,
)
EXP_FORCE_MN = np.array(
    [
        0.040,
        0.046,
        0.052,
        0.059,
        0.066,
        0.073,
        0.081,
        0.090,
        0.098,
        0.107,
        0.116,
        0.126,
        0.137,
        0.146,
        0.150,
        0.148,
        0.130,
        0.095,
        0.045,
        -0.020,
        -0.080,
        -0.160,
        -0.280,
        -0.380,
    ],
    dtype=float,
)
EXP_TIME_S = (APPROACH_START_D_OVER_R - EXP_D_OVER_R) * PARTICLE_RADIUS_M / GAP_RATE_MPS


def _build_cli() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, default=DEFAULT_RUN_DIR)
    parser.add_argument("--frame-dir-name", default=DEFAULT_FRAME_DIR_NAME)
    parser.add_argument("--history-file", default="approach_history_full.json")
    parser.add_argument("--output-name", default=DEFAULT_OUTPUT_NAME)
    parser.add_argument("--first-name", default=DEFAULT_FIRST_NAME)
    parser.add_argument("--duration-ms", type=int, default=140)
    parser.add_argument("--width", type=int, default=333)
    parser.add_argument("--base-top-height", type=int, default=178)
    parser.add_argument("--top-scale", type=float, default=1.20)
    parser.add_argument("--gap", type=int, default=7)
    parser.add_argument("--chart-height", type=int, default=178)
    parser.add_argument(
        "--resolution-scale",
        type=float,
        default=1.0,
        help="Scale the output pixel dimensions and chart styling together.",
    )
    parser.add_argument(
        "--font-scale",
        type=float,
        default=1.0,
        help="Additional scale factor for chart fonts and strokes.",
    )
    parser.add_argument(
        "--mesh-crop",
        nargs=4,
        type=int,
        metavar=("LEFT", "TOP", "RIGHT", "BOTTOM"),
        default=(10, 150, 690, 514),
        help="Crop box in the one-window diagnostic frame for the mesh panel.",
    )
    parser.add_argument(
        "--no-top-sphere-lock",
        action="store_true",
        help="Disable frame-to-frame visual anchoring of the fixed top sphere.",
    )
    return parser


def _configure_matplotlib() -> None:
    os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "matplotlib"))
    import matplotlib

    matplotlib.use("Agg")


def _load_history(path: Path) -> list[dict]:
    payload = json.loads(path.read_text())
    history = payload.get("history") if isinstance(payload, dict) else payload
    if not isinstance(history, list) or not history:
        raise RuntimeError(f"{path} does not contain a non-empty history list")
    return history


def _frame_paths(frame_dir: Path) -> list[tuple[int, Path]]:
    items: list[tuple[int, Path]] = []
    for path in sorted(frame_dir.glob("diagnostic_step*.png")):
        match = FRAME_RE.match(path.name)
        if match:
            items.append((int(match.group("step")), path))
    if not items:
        raise RuntimeError(f"No diagnostic_step*.png frames found in {frame_dir}")
    return items


def _fit_cover(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    image = image.convert("RGB")
    target_w, target_h = size
    scale = max(target_w / image.width, target_h / image.height)
    width = max(1, int(round(image.width * scale)))
    height = max(1, int(round(image.height * scale)))
    image = image.resize((width, height), Image.Resampling.LANCZOS)
    left = (width - target_w) // 2
    top = (height - target_h) // 2
    return image.crop((left, top, left + target_w, top + target_h))


def _top_sphere_anchor(image: Image.Image) -> tuple[float, float] | None:
    arr = np.asarray(image.convert("RGB"))
    height, width = arr.shape[:2]
    red = arr[..., 0].astype(np.int16)
    green = arr[..., 1].astype(np.int16)
    blue = arr[..., 2].astype(np.int16)
    max_rgb = np.maximum.reduce([red, green, blue])
    min_rgb = np.minimum.reduce([red, green, blue])
    saturation = max_rgb - min_rgb
    yy = np.indices((height, width))[0]
    mask = (
        (saturation < 28)
        & (max_rgb < 195)
        & (min_rgb > 45)
        & (yy < int(round(0.75 * height)))
    )
    visited = np.zeros(mask.shape, dtype=bool)
    best_count = 0
    best_bbox: tuple[int, int, int, int] | None = None
    for start_y, start_x in zip(*np.nonzero(mask)):
        if visited[start_y, start_x]:
            continue
        stack = [(int(start_y), int(start_x))]
        visited[start_y, start_x] = True
        count = 0
        min_x = max_x = int(start_x)
        min_y = max_y = int(start_y)
        while stack:
            y, x = stack.pop()
            count += 1
            min_x = min(min_x, x)
            max_x = max(max_x, x)
            min_y = min(min_y, y)
            max_y = max(max_y, y)
            for next_y, next_x in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
                if (
                    0 <= next_y < height
                    and 0 <= next_x < width
                    and mask[next_y, next_x]
                    and not visited[next_y, next_x]
                ):
                    visited[next_y, next_x] = True
                    stack.append((next_y, next_x))
        if count <= best_count:
            continue
        bbox_width = max_x - min_x + 1
        bbox_height = max_y - min_y + 1
        if bbox_width < max(12, int(round(0.25 * width))) or bbox_height < 5:
            continue
        if 0.5 * (min_y + max_y) > 0.65 * height:
            continue
        best_count = count
        best_bbox = (min_x, min_y, max_x, max_y)
    if best_bbox is None:
        return None
    left, top, right, _bottom = best_bbox
    return (0.5 * float(left + right), float(top))


def _shift_with_white_fill(image: Image.Image, dx: int, dy: int) -> Image.Image:
    if dx == 0 and dy == 0:
        return image
    shifted = Image.new("RGB", image.size, "white")
    shifted.paste(image, (int(dx), int(dy)))
    image.close()
    return shifted


def _series(history: list[dict]) -> tuple[np.ndarray, np.ndarray, dict[int, int]]:
    time_s = np.asarray([float(row["t"]) for row in history], dtype=float)
    force_mn = np.asarray([-float(row["fixed_force_axial"]) * 1.0e3 for row in history], dtype=float)
    step_to_index = {int(row["step"]): index for index, row in enumerate(history)}
    return time_s, force_mn, step_to_index


def _force_report_label(history: list[dict]) -> str:
    has_lubrication_wall_pressure = any(
        "lubrication_pressure" in str(row.get("force_model", ""))
        or abs(float(row.get("lubrication_pressure_force_n", 0.0))) > 0.0
        for row in history
    )
    if has_lubrication_wall_pressure:
        return "raw sim + lub. wall pressure"
    return "raw sim force report"


def _nearest_history_index(step_to_index: dict[int, int], step: int) -> int:
    if step in step_to_index:
        return step_to_index[step]
    steps = np.asarray(sorted(step_to_index), dtype=int)
    nearest_step = int(steps[int(np.argmin(np.abs(steps - int(step))))])
    return step_to_index[nearest_step]


def _draw_chart(
    *,
    step: int,
    time_s: np.ndarray,
    force_mn: np.ndarray,
    step_to_index: dict[int, int],
    size: tuple[int, int],
    font_scale: float,
    force_label: str,
    duration_marker: bool = True,
) -> Image.Image:
    _configure_matplotlib()
    import matplotlib.pyplot as plt

    width, height = size
    idx = _nearest_history_index(step_to_index, step)
    t_now = float(time_s[idx])
    f_now = float(force_mn[idx])

    x_min = min(float(np.min(time_s)), float(np.min(EXP_TIME_S)))
    x_max = max(float(np.max(time_s)), float(np.max(EXP_TIME_S)))
    y_min = min(float(np.min(force_mn)), float(np.min(EXP_FORCE_MN)), 0.0)
    y_max = max(float(np.max(force_mn)), float(np.max(EXP_FORCE_MN)), 0.0)
    x_pad = 0.02 * max(x_max - x_min, 1.0)
    y_pad = 0.08 * max(y_max - y_min, 1.0e-9)

    dpi = 160
    fig = plt.figure(figsize=(width / dpi, height / dpi), dpi=dpi)
    ax = fig.add_axes([0.145, 0.245, 0.815, 0.610])
    fs = max(float(font_scale), 0.1)
    ax.scatter(
        EXP_TIME_S,
        EXP_FORCE_MN,
        s=8 * fs * fs,
        facecolors="white",
        edgecolors="#111111",
        linewidths=0.6 * fs,
        label="Pitois Fig. 6 exp",
        zorder=3,
    )
    ax.plot(time_s, force_mn, color="#d62828", linewidth=1.2 * fs, label=force_label)
    ax.axhline(0.0, color="#777777", linewidth=0.55 * fs, linestyle="--", alpha=0.75)
    if duration_marker:
        ax.axvline(t_now, color="#555555", linewidth=0.55 * fs, alpha=0.45)
        ax.scatter([t_now], [f_now], s=9 * fs * fs, color="#d62828", zorder=4)
    ax.set_xlim(x_min - x_pad, x_max + x_pad)
    ax.set_ylim(y_min - y_pad, y_max + y_pad)
    ax.set_title("chart_vs_t: Pitois Fig. 6 force comparison", fontsize=5.6 * fs, pad=1.5 * fs)
    ax.set_xlabel("t [s]", fontsize=5.4 * fs, labelpad=1.0 * fs)
    ax.set_ylabel("F [mN]", fontsize=5.4 * fs, labelpad=1.0 * fs)
    ax.tick_params(axis="both", labelsize=4.8 * fs, length=2.0 * fs, pad=1.0 * fs)
    ax.grid(True, alpha=0.22, linewidth=0.35 * fs)
    ax.legend(fontsize=4.2 * fs, loc="lower left", frameon=False, handlelength=1.2)
    fig.canvas.draw()
    arr = np.asarray(fig.canvas.buffer_rgba())[..., :3].copy()
    plt.close(fig)
    return Image.fromarray(arr, mode="RGB")


def render_cover_gif(
    *,
    run_dir: Path,
    frame_dir: Path,
    history_path: Path,
    output_path: Path,
    first_path: Path,
    duration_ms: int,
    width: int,
    top_height: int,
    gap: int,
    chart_height: int,
    mesh_crop: tuple[int, int, int, int],
    font_scale: float,
    lock_top_sphere: bool,
) -> Path:
    history = _load_history(history_path)
    time_s, force_mn, step_to_index = _series(history)
    force_label = _force_report_label(history)
    frame_items = _frame_paths(frame_dir)
    total_height = int(top_height) + int(gap) + int(chart_height)

    frames: list[Image.Image] = []
    reference_anchor: tuple[float, float] | None = None
    for step, frame_path in frame_items:
        diagnostic = Image.open(frame_path).convert("RGB")
        try:
            mesh_panel = _fit_cover(diagnostic.crop(mesh_crop), (width, top_height))
        finally:
            diagnostic.close()
        if bool(lock_top_sphere):
            anchor = _top_sphere_anchor(mesh_panel)
            if anchor is not None and reference_anchor is None:
                reference_anchor = anchor
            elif anchor is not None and reference_anchor is not None:
                dx = int(round(reference_anchor[0] - anchor[0]))
                dy = int(round(reference_anchor[1] - anchor[1]))
                mesh_panel = _shift_with_white_fill(mesh_panel, dx, dy)
        chart_panel = _draw_chart(
            step=step,
            time_s=time_s,
            force_mn=force_mn,
            step_to_index=step_to_index,
            size=(width, chart_height),
            font_scale=font_scale,
            force_label=force_label,
        )
        canvas = Image.new("RGB", (width, total_height), "white")
        canvas.paste(mesh_panel, (0, 0))
        canvas.paste(chart_panel, (0, top_height + gap))
        mesh_panel.close()
        chart_panel.close()
        frames.append(canvas)

    first_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    frames[0].save(first_path)
    paletted = [frame.convert("P", palette=Image.Palette.ADAPTIVE) for frame in frames]
    try:
        paletted[0].save(
            output_path,
            save_all=True,
            append_images=paletted[1:],
            duration=int(duration_ms),
            loop=0,
            optimize=False,
            disposal=2,
        )
    finally:
        for frame in frames:
            frame.close()
        for frame in paletted:
            frame.close()
    print(output_path)
    print(first_path)
    print(f"frames={len(frame_items)} size={width}x{total_height}")
    return output_path


def main() -> None:
    args = _build_cli().parse_args()
    run_dir = args.run_dir.resolve()
    frame_dir = run_dir / str(args.frame_dir_name)
    history_path = run_dir / str(args.history_file)
    resolution_scale = max(float(args.resolution_scale), 0.1)
    width = int(round(int(args.width) * resolution_scale))
    top_height = int(round(float(args.base_top_height) * float(args.top_scale) * resolution_scale))
    gap = int(round(int(args.gap) * resolution_scale))
    chart_height = int(round(int(args.chart_height) * resolution_scale))
    render_cover_gif(
        run_dir=run_dir,
        frame_dir=frame_dir,
        history_path=history_path,
        output_path=run_dir / str(args.output_name),
        first_path=run_dir / str(args.first_name),
        duration_ms=int(args.duration_ms),
        width=width,
        top_height=top_height,
        gap=gap,
        chart_height=chart_height,
        mesh_crop=tuple(int(v) for v in args.mesh_crop),
        font_scale=max(float(args.font_scale), 0.1) * resolution_scale,
        lock_top_sphere=not bool(args.no_top_sphere_lock),
    )


if __name__ == "__main__":
    main()
