#!/usr/bin/env python3
"""Case 2b axisymmetric initial liquid-bridge shape generated by Gmsh.

This is the Gmsh-only counterpart of ``Case_2b_axisym_initialshape.py``.  It
does not import the separation workflow and it does not use HyperCT.  Gmsh owns
both the CAD geometry and the final volume mesh.

The liquid-air meridian is sampled by radius on each half bridge.  The radial
gaps are smallest at the contact line and grow away from it by the requested
ratio, matching the top-code convention used for the contact-line refinement.

Equation/reference map:
    Pitois, Moucheront, Chateau, J. Colloid Interface Sci. 231 (2000):
        source of the Fig. 5 geometry targets, bridge volume, separation D/R,
        and Eq. [6] contact-radius estimate behind this baseline rCL setting.
    Contact plane:
        z_cl = 1/2 [(D/R) R + 2 (R - sqrt(R^2 - r_CL^2))].
    Active free-surface profile:
        use_young_laplace_profile is False by default, so this script uses the
        smooth volume-matched analytic profile z/z_cl = 3 t^2 - 2 t^3 and then
        projects the meridian to the target volume.
    Optional Young-Laplace BVP:
        the code path is present for testing, with capillary pressure balance
        p ~ gamma kappa and hydrostatic term rho g z, but it is not the default
        mesh used by the canonical case runs.
    Volume:
        the meridian polygon volume is evaluated by Pappus' centroid theorem;
        the Gmsh tetrahedral mesh volume is then corrected against V = 1.10 mm^3.
"""

from __future__ import annotations

import csv
from dataclasses import asdict, dataclass, replace
import json
import math
import os
from pathlib import Path
import shutil

USER_TOTAL_ITERATIONS = 12
USER_RELAX_DT_S = 2.0e-5
USER_RELAX_DAMPING = 20.0
USER_FORCE_TOL_N = 1.0e-10
USER_TOTAL_FORCE_TOL_N = 1.0e-14
USER_SPEED_TOL_MPS = 1.0e-9
USER_MAX_ACCELERATION_MPS2 = 5.0e-3
# Single Gmsh mesh-density knob.  1.0 keeps the current mesh, 2.0 makes
# characteristic lengths half as large and doubles azimuthal sectors, and 0.5
# makes characteristic lengths twice as large and halves azimuthal sectors.
USER_MESH_DENSITY_FACTOR = 0.5
USER_OPEN_INTERACTIVE_WINDOW = True
USER_INTERACTIVE_STEP = USER_TOTAL_ITERATIONS
USER_INTERACTIVE_ELEV_DEG = 0# 18.0
USER_INTERACTIVE_AZIM_DEG = 90# -58.0

os.environ.setdefault("MPLCONFIGDIR", "/tmp/ddgclib-mpl")
import matplotlib
if not USER_OPEN_INTERACTIVE_WINDOW:
    matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

try:
    from scipy.integrate import solve_bvp
except ImportError:  # pragma: no cover - the analytic fallback still works.
    solve_bvp = None

try:
    from scipy.interpolate import PchipInterpolator
except ImportError:  # pragma: no cover - plotting falls back to linear interpolation.
    PchipInterpolator = None


@dataclass(frozen=True)
class Case2bGmshConfig:
    # Case 2b physical geometry, copied from the axisymmetric initial-shape
    # setup without importing the HyperCT-backed separation module.
    particle_radius_m: float = 4.0e-3
    contact_radius_m: float = 1.54e-3
    initial_d_over_r: float = 0.014484537138212631
    bridge_volume_m3: float = 1.10e-9
    gamma_n_per_m: float = 2.10e-2
    rho_kg_per_m3: float = 965.0
    gravity_mps2: float = 9.80665

    # Geometry sampling.
    sphere_arc_nodes: int = 13
    free_surface_half_nodes: int = 16
    free_surface_radial_ratio: float = 1.1
    use_young_laplace_profile: bool = False
    sphere_clearance_fraction: float = 0.90
    total_iterations: int = USER_TOTAL_ITERATIONS
    relax_dt_s: float = USER_RELAX_DT_S
    relax_damping: float = USER_RELAX_DAMPING
    force_tol_n: float = USER_FORCE_TOL_N
    total_force_tol_n: float = USER_TOTAL_FORCE_TOL_N
    speed_tol_mps: float = USER_SPEED_TOL_MPS
    max_acceleration_mps2: float = USER_MAX_ACCELERATION_MPS2
    step_max_retries: int = 3
    step_retry_dt_scale: float = 0.5
    max_step_fraction: float = 0.12
    open_interactive_window: bool = USER_OPEN_INTERACTIVE_WINDOW
    interactive_step: int = USER_INTERACTIVE_STEP
    interactive_elev_deg: float = USER_INTERACTIVE_ELEV_DEG
    interactive_azim_deg: float = USER_INTERACTIVE_AZIM_DEG
    mesh_volume_correction_max_passes: int = 10
    mesh_volume_correction_rel_tol: float = 1.0e-6

    # Mesh sizes.
    mesh_density_factor: float = USER_MESH_DENSITY_FACTOR
    azimuthal_nodes: int = 32
    lc_contact_line_m: float = 7.5e-5
    lc_liquid_air_m: float = 1.2e-4
    lc_cap_m: float = 1.6e-4
    lc_bulk_m: float = 3.8e-4
    contact_line_growth_steps: int = 14

    # Output.
    out_dir: str = "out/Case_2b_axisym_initialshape_Gmsh"
    name: str = "Case_2b_axisym_initialshape_Gmsh"


_REFERENCE_FIG1_U = np.array(
    [0.0, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.0],
    dtype=float,
)
_REFERENCE_FIG1_R_RATIO = np.array(
    [
        0.4812155844,
        0.4957889610,
        0.5385564935,
        0.6066590909,
        0.6953305195,
        0.7978987013,
        0.9057857143,
        1.0085058442,
        1.0000000000,
    ],
    dtype=float,
)


def _contact_plane_half_gap(c: Case2bGmshConfig) -> float:
    axial_offset = math.sqrt(max(c.particle_radius_m**2 - c.contact_radius_m**2, 0.0))
    surface_gap = c.initial_d_over_r * c.particle_radius_m
    contact_plane_gap = surface_gap + 2.0 * (c.particle_radius_m - axial_offset)
    return 0.5 * contact_plane_gap


def _sphere_center_z(c: Case2bGmshConfig, *, top: bool) -> float:
    axial_offset = math.sqrt(max(c.particle_radius_m**2 - c.contact_radius_m**2, 0.0))
    sign = 1.0 if top else -1.0
    return sign * (_contact_plane_half_gap(c) + axial_offset)


def _sphere_z(r: np.ndarray, c: Case2bGmshConfig, *, top: bool) -> np.ndarray:
    zc = _sphere_center_z(c, top=top)
    dz = np.sqrt(np.maximum(c.particle_radius_m**2 - np.asarray(r, dtype=float) ** 2, 0.0))
    return zc - dz if top else zc + dz


def _polygon_area_centroid_r(poly_rz: np.ndarray) -> tuple[float, float]:
    r = poly_rz[:, 0]
    z = poly_rz[:, 1]
    r_next = np.roll(r, -1)
    z_next = np.roll(z, -1)
    cross = r * z_next - r_next * z
    area_signed = 0.5 * float(np.sum(cross))
    if abs(area_signed) <= 1.0e-30:
        return 0.0, 0.0
    centroid_r = float(np.sum((r + r_next) * cross) / (6.0 * area_signed))
    return abs(area_signed), abs(centroid_r)


def _volume_from_meridian_polygon(poly_rz: np.ndarray) -> float:
    area, centroid_r = _polygon_area_centroid_r(poly_rz)
    return 2.0 * math.pi * area * centroid_r


def _radially_biased_half_samples(
    z_from_profile: np.ndarray,
    r_from_profile: np.ndarray,
    *,
    n_samples: int,
    contact_radius: float,
    ratio: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return neck-to-contact samples with smallest radial gap at the CL."""
    z_arr = np.asarray(z_from_profile, dtype=float)
    r_arr = np.asarray(r_from_profile, dtype=float)
    finite = np.isfinite(z_arr) & np.isfinite(r_arr)
    z_arr = z_arr[finite]
    r_arr = r_arr[finite]
    if z_arr.size < 2 or int(n_samples) < 2:
        return z_arr, r_arr

    order = np.argsort(z_arr)
    z_arr = z_arr[order]
    r_arr = np.maximum.accumulate(r_arr[order])
    r_arr[-1] = float(contact_radius)

    unique_r, unique_idx = np.unique(np.round(r_arr, decimals=15), return_index=True)
    if unique_r.size < 2:
        z_samples = np.linspace(float(z_arr[0]), float(z_arr[-1]), int(n_samples), dtype=float)
        return z_samples, np.interp(z_samples, z_arr, r_arr)

    keep = np.sort(unique_idx)
    z_unique = z_arr[keep]
    r_unique = r_arr[keep]
    r_neck = float(r_unique[0])
    r_cl = float(contact_radius)
    if r_cl <= r_neck or abs(float(ratio) - 1.0) <= 1.0e-12:
        z_samples = np.linspace(float(z_unique[0]), float(z_unique[-1]), int(n_samples), dtype=float)
        return z_samples, np.interp(z_samples, z_unique, r_unique)

    n_gaps = int(n_samples) - 1
    # Gaps are ordered from neck -> CL.  The first gap is largest and each
    # subsequent gap is divided by ratio, so the CL side is finest.
    weights = float(ratio) ** np.arange(n_gaps - 1, -1, -1, dtype=float)
    radial_gaps = (r_cl - r_neck) * weights / float(np.sum(weights))
    r_samples = np.concatenate([[r_neck], r_neck + np.cumsum(radial_gaps)])
    r_samples[-1] = r_cl
    z_samples = np.interp(r_samples, r_unique, z_unique)
    z_samples[0] = float(z_unique[0])
    z_samples[-1] = float(z_unique[-1])
    return z_samples, r_samples


def _reference_half_profile(c: Case2bGmshConfig, radial_scale: float) -> tuple[np.ndarray, np.ndarray]:
    z_cl = _contact_plane_half_gap(c)
    u = np.linspace(0.0, 1.0, 400, dtype=float)
    r_ratio = np.interp(u, _REFERENCE_FIG1_U, _REFERENCE_FIG1_R_RATIO)
    r = np.clip(radial_scale * c.contact_radius_m * r_ratio, 1.0e-8 * c.contact_radius_m, c.contact_radius_m)
    r[-1] = c.contact_radius_m
    return z_cl * u, r


def _sphere_limited_analytic_half_profile(c: Case2bGmshConfig) -> tuple[np.ndarray, np.ndarray]:
    """Volume-match a smooth half-profile while keeping it inside the spheres."""

    def samples_for_neck(neck_radius: float) -> tuple[np.ndarray, np.ndarray]:
        n_samples = max(2, int(c.free_surface_half_nodes))
        n_gaps = n_samples - 1
        ratio = max(1.0, float(c.free_surface_radial_ratio))
        if abs(ratio - 1.0) <= 1.0e-12:
            r = np.linspace(float(neck_radius), c.contact_radius_m, n_samples, dtype=float)
        else:
            weights = ratio ** np.arange(n_gaps - 1, -1, -1, dtype=float)
            gaps = (c.contact_radius_m - float(neck_radius)) * weights / float(np.sum(weights))
            r = np.concatenate([[float(neck_radius)], float(neck_radius) + np.cumsum(gaps)])
            r[-1] = c.contact_radius_m

        t = (r - float(neck_radius)) / max(c.contact_radius_m - float(neck_radius), 1.0e-30)
        smooth = 3.0 * t * t - 2.0 * t * t * t
        z = _contact_plane_half_gap(c) * smooth
        sphere_limit = max(0.1, min(float(c.sphere_clearance_fraction), 0.999)) * _sphere_z(r, c, top=True)
        z[:-1] = np.minimum(z[:-1], sphere_limit[:-1])
        z[0] = 0.0
        z[-1] = _contact_plane_half_gap(c)
        return z, r

    lo = 1.0e-8 * c.contact_radius_m
    hi = 0.999 * c.contact_radius_m
    for _ in range(64):
        mid = 0.5 * (lo + hi)
        z_mid, r_mid = samples_for_neck(mid)
        volume = _volume_from_meridian_polygon(_make_meridian_polygon_from_half(c, z_mid, r_mid))
        if volume < c.bridge_volume_m3:
            lo = mid
        else:
            hi = mid

    return samples_for_neck(0.5 * (lo + hi))


def _young_laplace_half_profile(c: Case2bGmshConfig) -> tuple[np.ndarray, np.ndarray] | None:
    if solve_bvp is None:
        return None

    z_cl = _contact_plane_half_gap(c)
    target_half_volume = 0.5 * c.bridge_volume_m3
    xi = np.linspace(0.0, 1.0, 300, dtype=float)
    mid_radius_guess = 0.5e-3
    r_guess = mid_radius_guess + (c.contact_radius_m - mid_radius_guess) * np.power(xi, 1.4)
    z_guess = z_cl * xi
    psi_guess = np.linspace(np.pi / 2.0, 0.6, xi.size, dtype=float)
    vol_guess = np.pi * np.cumsum(
        np.concatenate([[0.0], 0.5 * (r_guess[1:] ** 2 + r_guess[:-1] ** 2) * np.diff(z_guess)])
    )
    y_guess = np.vstack([r_guess, z_guess, psi_guess, vol_guess])

    def fun(_xi: np.ndarray, y: np.ndarray, p: np.ndarray) -> np.ndarray:
        pressure_offset = float(p[0])
        arc_length_end = float(p[1])
        r = np.maximum(y[0], 1.0e-12)
        z = y[1]
        psi = y[2]
        two_gamma = (pressure_offset - c.rho_kg_per_m3 * c.gravity_mps2 * z) / c.gamma_n_per_m
        return np.vstack(
            [
                arc_length_end * np.cos(psi),
                arc_length_end * np.sin(psi),
                arc_length_end * (two_gamma - np.sin(psi) / r),
                arc_length_end * np.pi * r * r * np.sin(psi),
            ]
        )

    def bc(ya: np.ndarray, yb: np.ndarray, _p: np.ndarray) -> np.ndarray:
        return np.array(
            [
                ya[1],
                ya[2] - np.pi / 2.0,
                ya[3],
                yb[0] - c.contact_radius_m,
                yb[1] - z_cl,
                yb[3] - target_half_volume,
            ],
            dtype=float,
        )

    sol = solve_bvp(
        fun,
        bc,
        xi,
        y_guess,
        p=np.array([-35.0, 1.1e-3], dtype=float),
        max_nodes=50000,
        tol=1.0e-4,
    )
    if not bool(sol.success):
        return None

    z = np.asarray(sol.y[1], dtype=float)
    r = np.asarray(sol.y[0], dtype=float)
    finite = np.isfinite(z) & np.isfinite(r)
    z = z[finite]
    r = np.clip(r[finite], 1.0e-8 * c.contact_radius_m, c.contact_radius_m)
    order = np.argsort(z)
    z = z[order]
    r = r[order]
    r[-1] = c.contact_radius_m
    return z, r


def _free_surface_samples(c: Case2bGmshConfig) -> tuple[np.ndarray, np.ndarray, str]:
    profile = _young_laplace_half_profile(c) if bool(c.use_young_laplace_profile) else None
    source = "young_laplace_bvp"
    if profile is None:
        source = "sphere_limited_analytic_volume_matched"
        profile = _sphere_limited_analytic_half_profile(c)

    z_half, r_half = profile
    z_samples, r_samples = _radially_biased_half_samples(
        z_half,
        r_half,
        n_samples=c.free_surface_half_nodes,
        contact_radius=c.contact_radius_m,
        ratio=c.free_surface_radial_ratio,
    )
    return z_samples, r_samples, source


def _make_meridian_polygon_from_half(
    c: Case2bGmshConfig,
    z_half: np.ndarray,
    r_half: np.ndarray,
) -> np.ndarray:
    r_cl = c.contact_radius_m
    r_bottom = np.linspace(0.0, r_cl, c.sphere_arc_nodes, dtype=float)
    z_bottom = _sphere_z(r_bottom, c, top=False)
    z_bottom[0] = -0.5 * c.initial_d_over_r * c.particle_radius_m

    r_top = np.linspace(r_cl, 0.0, c.sphere_arc_nodes, dtype=float)
    z_top = _sphere_z(r_top, c, top=True)
    z_top[-1] = 0.5 * c.initial_d_over_r * c.particle_radius_m

    z_free_bottom = -np.asarray(z_half[::-1], dtype=float)
    r_free_bottom = np.asarray(r_half[::-1], dtype=float)
    z_free_top = np.asarray(z_half, dtype=float)
    r_free_top = np.asarray(r_half, dtype=float)

    poly: list[tuple[float, float]] = []
    poly.extend(zip(r_bottom, z_bottom))
    # Omit the midplane neck point from the CAD loop.  Keeping that single
    # point makes the two free-surface branches meet as a visible V; omitting it
    # connects the adjacent lower/upper interface vertices directly.
    poly.extend(zip(r_free_bottom[1:-1], z_free_bottom[1:-1]))
    poly.extend(zip(r_free_top[1:], z_free_top[1:]))
    poly.extend(zip(r_top[1:], z_top[1:]))

    return np.asarray(poly, dtype=float)


def _mesh_density_factor(c: Case2bGmshConfig) -> float:
    return max(float(c.mesh_density_factor), 1.0e-6)


def _scaled_mesh_lc(c: Case2bGmshConfig, base_lc_m: float) -> float:
    return float(base_lc_m) / _mesh_density_factor(c)


def _scaled_azimuthal_sectors(c: Case2bGmshConfig) -> int:
    requested = max(4, int(round(float(c.azimuthal_nodes) * _mesh_density_factor(c))))
    return int(4 * max(1, int(round(float(requested) / 4.0))))


def _add_polyline_loop(gmsh, poly_rz: np.ndarray, c: Case2bGmshConfig) -> tuple[list[int], list[int]]:
    point_tags: list[int] = []
    n_poly = len(poly_rz)
    bottom_cl_idx = c.sphere_arc_nodes - 1
    top_cl_idx = c.sphere_arc_nodes + 2 * c.free_surface_half_nodes - 3

    for idx, (r, z) in enumerate(poly_rz):
        if idx in (bottom_cl_idx, top_cl_idx):
            lc = _scaled_mesh_lc(c, c.lc_contact_line_m)
        elif bottom_cl_idx < idx < top_cl_idx:
            lc = _scaled_mesh_lc(c, c.lc_liquid_air_m)
        elif abs(float(r)) <= 1.0e-14:
            lc = _scaled_mesh_lc(c, c.lc_bulk_m)
        else:
            lc = _scaled_mesh_lc(c, c.lc_cap_m)
        point_tags.append(gmsh.model.occ.addPoint(float(r), 0.0, float(z), float(lc)))

    line_tags = [
        gmsh.model.occ.addLine(point_tags[idx], point_tags[(idx + 1) % n_poly])
        for idx in range(n_poly)
    ]
    return point_tags, line_tags


def _add_polyline_loop_geo(gmsh, poly_rz: np.ndarray, c: Case2bGmshConfig) -> tuple[list[int], list[int]]:
    point_tags: list[int] = []
    n_poly = len(poly_rz)
    bottom_cl_idx = c.sphere_arc_nodes - 1
    top_cl_idx = c.sphere_arc_nodes + 2 * c.free_surface_half_nodes - 3

    geo = gmsh.model.geo
    for idx, (r, z) in enumerate(poly_rz):
        if idx in (bottom_cl_idx, top_cl_idx):
            lc = _scaled_mesh_lc(c, c.lc_contact_line_m)
        elif bottom_cl_idx < idx < top_cl_idx:
            lc = _scaled_mesh_lc(c, c.lc_liquid_air_m)
        elif abs(float(r)) <= 1.0e-14:
            lc = _scaled_mesh_lc(c, c.lc_bulk_m)
        else:
            lc = _scaled_mesh_lc(c, c.lc_cap_m)
        point_tags.append(geo.addPoint(float(r), 0.0, float(z), float(lc)))

    line_tags = [
        geo.addLine(point_tags[idx], point_tags[(idx + 1) % n_poly])
        for idx in range(n_poly)
    ]
    return point_tags, line_tags


def _element_tet_subdivision(element_name: str, row: list[int]) -> list[list[int]]:
    if element_name.startswith("Tetrahedron") and len(row) >= 4:
        return [row[:4]]
    if element_name.startswith("Pyramid") and len(row) >= 5:
        a, b, c, d, apex = row[:5]
        return [[a, b, c, apex], [a, c, d, apex]]
    if element_name.startswith("Prism") and len(row) >= 6:
        a, b, c, d, e, f = row[:6]
        return [[a, b, c, d], [b, c, d, e], [c, d, e, f]]
    if element_name.startswith("Hexahedron") and len(row) >= 8:
        a, b, c, d, e, f, g, h = row[:8]
        return [
            [a, b, d, e],
            [b, c, d, g],
            [b, d, e, g],
            [b, e, f, g],
            [d, e, g, h],
        ]
    return []


def _extract_gmsh_mesh_arrays(gmsh) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, int]]:
    node_tags, coords, _params = gmsh.model.mesh.getNodes()
    node_tags = np.asarray(node_tags, dtype=np.int64)
    coords = np.asarray(coords, dtype=float).reshape((-1, 3))
    tag_to_idx = {int(tag): idx for idx, tag in enumerate(node_tags)}

    tris: list[list[int]] = []
    tets: list[list[int]] = []
    element_counts: dict[str, int] = {}
    for dim in (2, 3):
        elem_types, _elem_tags, elem_nodes = gmsh.model.mesh.getElements(dim)
        for elem_type, nodes_flat in zip(elem_types, elem_nodes):
            name, _edim, _order, n_nodes, _local, _n_primary = gmsh.model.mesh.getElementProperties(elem_type)
            nodes = np.asarray(nodes_flat, dtype=np.int64).reshape((-1, int(n_nodes)))
            element_counts[str(name)] = element_counts.get(str(name), 0) + int(nodes.shape[0])
            for raw_row in nodes:
                row = [tag_to_idx[int(tag)] for tag in raw_row]
                if dim == 2 and int(n_nodes) == 3:
                    tris.append(row[:3])
                elif dim == 2 and int(n_nodes) == 4:
                    a, b, c_, d = row[:4]
                    tris.extend([[a, b, c_], [a, c_, d]])
                elif dim == 3:
                    tets.extend(_element_tet_subdivision(str(name), row))

    return (
        coords,
        np.asarray(tris, dtype=int),
        np.asarray(tets, dtype=int),
        node_tags,
        element_counts,
    )


def _write_tet_volume_csv(points: np.ndarray, tets: np.ndarray, node_tags: np.ndarray, out_path: Path) -> Path:
    csv_path = out_path.with_name(f"{out_path.stem}_tet_volumes.csv")
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "tet_id",
                "node1_id",
                "node2_id",
                "node3_id",
                "node4_id",
                "x1_m",
                "y1_m",
                "z1_m",
                "x2_m",
                "y2_m",
                "z2_m",
                "x3_m",
                "y3_m",
                "z3_m",
                "x4_m",
                "y4_m",
                "z4_m",
                "signed_volume_m3",
                "tet_volume_m3",
                "tet_volume_mm3",
                "tet_volume_uL",
            ]
        )
        for tet_id, (a, b, c, d) in enumerate(np.asarray(tets, dtype=int), start=1):
            pa = np.asarray(points[int(a)], dtype=float)
            pb = np.asarray(points[int(b)], dtype=float)
            pc = np.asarray(points[int(c)], dtype=float)
            pd = np.asarray(points[int(d)], dtype=float)
            signed_volume = float(np.dot(pa - pd, np.cross(pb - pd, pc - pd)) / 6.0)
            tet_volume = abs(signed_volume)
            writer.writerow(
                [
                    tet_id,
                    int(node_tags[int(a)]),
                    int(node_tags[int(b)]),
                    int(node_tags[int(c)]),
                    int(node_tags[int(d)]),
                    f"{pa[0]:.17g}",
                    f"{pa[1]:.17g}",
                    f"{pa[2]:.17g}",
                    f"{pb[0]:.17g}",
                    f"{pb[1]:.17g}",
                    f"{pb[2]:.17g}",
                    f"{pc[0]:.17g}",
                    f"{pc[1]:.17g}",
                    f"{pc[2]:.17g}",
                    f"{pd[0]:.17g}",
                    f"{pd[1]:.17g}",
                    f"{pd[2]:.17g}",
                    f"{signed_volume:.17g}",
                    f"{tet_volume:.17g}",
                    f"{1.0e9 * tet_volume:.17g}",
                    f"{1.0e9 * tet_volume:.17g}",
                ]
            )
    return csv_path


def _write_snapshot_msh(points: np.ndarray, tets: np.ndarray, node_tags: np.ndarray, out_path: Path) -> Path:
    msh_path = out_path.with_suffix(".msh")
    pts = np.asarray(points, dtype=float)
    tet_idx = np.asarray(tets, dtype=int)
    tags = np.asarray(node_tags, dtype=np.int64)
    msh_path.parent.mkdir(parents=True, exist_ok=True)
    with open(msh_path, "w", encoding="utf-8") as f:
        f.write("$MeshFormat\n2.2 0 8\n$EndMeshFormat\n")
        f.write("$Nodes\n")
        f.write(f"{len(pts)}\n")
        for local_idx, p in enumerate(pts):
            tag = int(tags[local_idx]) if local_idx < len(tags) else local_idx + 1
            f.write(f"{tag} {p[0]:.17g} {p[1]:.17g} {p[2]:.17g}\n")
        f.write("$EndNodes\n")
        f.write("$Elements\n")
        f.write(f"{len(tet_idx)}\n")
        for elem_id, tet in enumerate(tet_idx, start=1):
            node_ids = [int(tags[int(i)]) if int(i) < len(tags) else int(i) + 1 for i in tet]
            f.write(f"{elem_id} 4 2 1 1 {node_ids[0]} {node_ids[1]} {node_ids[2]} {node_ids[3]}\n")
        f.write("$EndElements\n")
    return msh_path


def _set_axes_equal(ax, pts_mm: np.ndarray) -> None:
    if pts_mm.size == 0:
        return
    mins = np.min(pts_mm, axis=0)
    maxs = np.max(pts_mm, axis=0)
    center = 0.5 * (mins + maxs)
    radius = 0.5 * float(np.max(maxs - mins))
    radius = max(radius, 1.0e-9)
    ax.set_xlim(center[0] - radius, center[0] + radius)
    ax.set_ylim(center[1] - radius, center[1] + radius)
    ax.set_zlim(center[2] - radius, center[2] + radius)
    ax.set_box_aspect((1, 1, 1))


def _interface_mesh_from_profile(
    *,
    z_half: np.ndarray,
    r_half: np.ndarray,
    c: Case2bGmshConfig,
) -> tuple[np.ndarray, np.ndarray]:
    z_profile, r_profile = _full_free_surface_from_half(z_half, r_half)
    if z_profile.size < 2 or r_profile.size != z_profile.size:
        return np.empty((0, 3), dtype=float), np.empty((0, 3), dtype=int)

    n_sectors = _scaled_azimuthal_sectors(c)
    theta = np.linspace(0.0, 2.0 * math.pi, n_sectors, endpoint=False, dtype=float)
    rings: list[np.ndarray] = []
    for r, z in zip(r_profile, z_profile):
        rings.append(
            np.column_stack(
                [
                    float(r) * np.cos(theta),
                    float(r) * np.sin(theta),
                    np.full(theta.shape, float(z), dtype=float),
                ]
            )
        )
    points = np.vstack(rings)

    triangles: list[list[int]] = []
    for ring in range(len(rings) - 1):
        base0 = ring * n_sectors
        base1 = (ring + 1) * n_sectors
        for sector in range(n_sectors):
            nxt = (sector + 1) % n_sectors
            a = base0 + sector
            b = base0 + nxt
            c_ = base1 + sector
            d = base1 + nxt
            triangles.append([a, c_, b])
            triangles.append([b, c_, d])

    return points, np.asarray(triangles, dtype=int)


def _draw_mesh_axes(
    ax,
    points: np.ndarray,
    triangles: np.ndarray,
    *,
    title: str,
    elev: float,
    azim: float,
) -> None:
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection

    pts_mm = 1.0e3 * np.asarray(points, dtype=float)
    tri_idx = np.asarray(triangles, dtype=int)
    if tri_idx.size:
        tri_xyz = pts_mm[tri_idx]
        collection = Poly3DCollection(
            tri_xyz,
            facecolors=(0.50, 0.72, 0.92, 0.22),
            edgecolors=(0.02, 0.02, 0.02, 0.55),
            linewidths=0.35,
        )
        ax.add_collection3d(collection)
        plot_pts = tri_xyz.reshape((-1, 3))
    else:
        plot_pts = pts_mm

    ax.set_title(title, pad=12)
    ax.set_xlabel("x [mm]")
    ax.set_ylabel("y [mm]")
    ax.set_zlabel("z [mm]")
    ax.set_proj_type("ortho")
    ax.view_init(elev=float(elev), azim=float(azim))
    _set_axes_equal(ax, plot_pts)
    ax.grid(True, alpha=0.28)


def _render_mesh_png(
    points: np.ndarray,
    triangles: np.ndarray,
    out_path: Path,
    *,
    title: str,
    elev: float = 18.0,
    azim: float = -58.0,
) -> Path:
    fig = plt.figure(figsize=(8.0, 8.0))
    ax = fig.add_subplot(111, projection="3d")
    _draw_mesh_axes(ax, points, triangles, title=title, elev=elev, azim=azim)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=180)
    plt.close(fig)
    return out_path


def _rounded_interface_profile(
    *,
    z_half: np.ndarray,
    r_half: np.ndarray,
    n_profile: int = 33,
) -> tuple[np.ndarray, np.ndarray]:
    z_half_arr = np.asarray(z_half, dtype=float)
    r_half_arr = np.asarray(r_half, dtype=float)
    order = np.argsort(z_half_arr)
    z_half_arr = z_half_arr[order]
    r_half_arr = r_half_arr[order]
    z_contact = max(float(z_half_arr[-1]), 1.0e-30)
    neck_radius = float(r_half_arr[0])
    contact_radius = float(r_half_arr[-1])

    z = np.linspace(-z_contact, z_contact, int(n_profile), dtype=float)
    z = z[np.abs(z) > 1.0e-12 * z_contact]
    if z.size < 2:
        z = np.array([-z_contact, z_contact], dtype=float)
    u = np.abs(z) / z_contact
    rounded_cap = 1.0 - np.sqrt(np.maximum(1.0 - u * u, 0.0))
    r = neck_radius + (contact_radius - neck_radius) * rounded_cap
    return z, r


def _draw_interface_mesh_axes(
    ax,
    *,
    z_half: np.ndarray,
    r_half: np.ndarray,
    title: str,
    n_sectors: int,
) -> None:
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection

    z_profile, r_profile = _rounded_interface_profile(
        z_half=z_half,
        r_half=r_half,
        n_profile=max(17, int(len(np.asarray(z_half)) * 2 - 1)),
    )
    n_sectors = max(8, int(n_sectors))
    theta = np.linspace(0.0, 2.0 * math.pi, n_sectors, endpoint=False, dtype=float)

    rings = []
    for r, z in zip(r_profile, z_profile):
        rings.append(
            np.column_stack(
                [
                    float(r) * np.cos(theta),
                    float(r) * np.sin(theta),
                    np.full(theta.shape, float(z), dtype=float),
                ]
            )
        )
    points = np.asarray(rings, dtype=float)
    points_mm = 1.0e3 * points

    triangles = []
    for j in range(points_mm.shape[0] - 1):
        for i in range(n_sectors):
            nxt = (i + 1) % n_sectors
            a = points_mm[j, i]
            b = points_mm[j, nxt]
            c_ = points_mm[j + 1, i]
            d = points_mm[j + 1, nxt]
            triangles.append([a, c_, b])
            triangles.append([b, c_, d])

    ax.add_collection3d(
        Poly3DCollection(
            triangles,
            facecolors=(0.50, 0.72, 0.92, 0.22),
            edgecolors="#111111",
            linewidths=0.42,
            alpha=0.95,
        )
    )
    ax.scatter(
        points_mm[:, :, 0].ravel(),
        points_mm[:, :, 1].ravel(),
        points_mm[:, :, 2].ravel(),
        s=5.0,
        color="#111111",
        alpha=0.75,
    )

    flat = points_mm.reshape((-1, 3))
    _set_axes_equal(ax, flat)
    ax.set_title(title, pad=12)
    ax.set_xlabel("x [mm]")
    ax.set_ylabel("y [mm]")
    ax.set_zlabel("z [mm]")
    ax.set_proj_type("ortho")
    ax.view_init(elev=22.0, azim=-55.0)
    ax.grid(True, alpha=0.28)


def _show_interactive_interface_mesh(
    *,
    z_half: np.ndarray,
    r_half: np.ndarray,
    title: str,
    n_sectors: int,
) -> None:
    fig = plt.figure(figsize=(9.0, 7.5))
    ax = fig.add_subplot(111, projection="3d")
    _draw_interface_mesh_axes(ax, z_half=z_half, r_half=r_half, title=title, n_sectors=n_sectors)
    plt.show()


def _render_interface_mesh_png(
    *,
    z_half: np.ndarray,
    r_half: np.ndarray,
    out_path: Path,
    title: str,
    n_sectors: int,
) -> Path:
    fig = plt.figure(figsize=(8.0, 8.0))
    ax = fig.add_subplot(111, projection="3d")
    _draw_interface_mesh_axes(ax, z_half=z_half, r_half=r_half, title=title, n_sectors=n_sectors)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=180)
    plt.close(fig)
    return out_path


def _show_interactive_mesh(
    points: np.ndarray,
    triangles: np.ndarray,
    *,
    title: str,
    elev: float,
    azim: float,
) -> None:
    fig = plt.figure(figsize=(9.0, 7.5))
    ax = fig.add_subplot(111, projection="3d")
    _draw_mesh_axes(ax, points, triangles, title=title, elev=elev, azim=azim)
    plt.show()


def _remove_midplane_surface_ring(
    points: np.ndarray,
    triangles: np.ndarray,
    *,
    r_neck: float,
) -> tuple[np.ndarray, np.ndarray]:
    pts = np.asarray(points, dtype=float)
    tri_idx = np.asarray(triangles, dtype=int)
    if pts.size == 0 or tri_idx.size == 0:
        return pts, tri_idx

    rho = np.linalg.norm(pts[:, :2], axis=1)
    tol_z = 2.0e-8
    tol_r = max(8.0e-5, 0.10 * float(r_neck))
    drop_node = (np.abs(pts[:, 2]) <= tol_z) & (np.abs(rho - float(r_neck)) <= tol_r)
    keep_tri = ~np.any(drop_node[tri_idx], axis=1)
    return pts, tri_idx[keep_tri]


def _write_snapshot_artifacts(
    *,
    points: np.ndarray,
    triangles: np.ndarray,
    tets: np.ndarray,
    node_tags: np.ndarray,
    out_base: Path,
    title: str,
    c: Case2bGmshConfig,
    z_half: np.ndarray,
    r_half: np.ndarray,
    elev: float = 18.0,
    azim: float = -58.0,
) -> dict[str, str]:
    png_path = out_base.with_suffix(".png")
    interface_mesh_png_path = out_base.with_name(f"{out_base.name}_interface_mesh.png")
    del triangles
    _render_interface_mesh_png(
        z_half=z_half,
        r_half=r_half,
        out_path=png_path,
        title=f"{title}: triangular interface mesh",
        n_sectors=_scaled_azimuthal_sectors(c),
    )
    _render_interface_mesh_png(
        z_half=z_half,
        r_half=r_half,
        out_path=interface_mesh_png_path,
        title=f"{title}: interface mesh",
        n_sectors=_scaled_azimuthal_sectors(c),
    )
    csv_path = _write_tet_volume_csv(points, tets, node_tags, out_base)
    msh_path = _write_snapshot_msh(points, tets, node_tags, out_base)
    return {
        "png": str(png_path),
        "interface_mesh_png": str(interface_mesh_png_path),
        "msh": str(msh_path),
        "tet_volume_csv": str(csv_path),
    }


def _render_equilibrium_history_figures(history: list[dict], fig_dir: Path) -> list[str]:
    if not history:
        return []

    fig_dir.mkdir(parents=True, exist_ok=True)
    steps = np.asarray([float(row["step"]) for row in history], dtype=float)
    time_ms = np.asarray([1.0e3 * float(row.get("time_s", 0.0)) for row in history], dtype=float)
    if np.allclose(time_ms, time_ms[0]) and steps.size > 1:
        time_ms = steps
        x_label = "Step"
    else:
        x_label = "Time [ms]"

    max_free_force = np.asarray([float(row.get("max_free_force_norm_n", 0.0)) for row in history], dtype=float)
    total_force = np.asarray([float(row.get("net_total_force_norm_n", 0.0)) for row in history], dtype=float)
    max_free_speed = np.asarray([float(row.get("max_free_speed_mps", 0.0)) for row in history], dtype=float)
    snapshot_volume_ul = np.asarray([float(row["snapshot_msh_volume_ul"]) for row in history], dtype=float)
    snapshot_volume_rel_frac = np.asarray([float(row["snapshot_msh_volume_rel_error"]) for row in history], dtype=float)
    target_volume_ul = float(snapshot_volume_ul[0] / (1.0 + snapshot_volume_rel_frac[0]))
    snapshot_volume_delta_pl = 1.0e6 * (snapshot_volume_ul - target_volume_ul)
    snapshot_volume_rel_percent = 100.0 * snapshot_volume_rel_frac

    def maybe_log(ax, values: np.ndarray) -> None:
        if np.any(np.asarray(values, dtype=float) > 0.0):
            ax.set_yscale("log")

    paths: list[Path] = []

    fig1, ax1 = plt.subplots(figsize=(7.0, 4.6))
    ax1.plot(time_ms, max_free_force, color="#bc4749", linewidth=1.8, marker="o", markersize=3.8)
    maybe_log(ax1, max_free_force)
    ax1.set_xlabel(x_label)
    ax1.set_ylabel("Max free-force norm [N]")
    ax1.set_title("Gmsh initial mesh: local force residual")
    ax1.grid(alpha=0.28, which="both")
    path1 = fig_dir / "equilibrium_max_free_force_vs_t.png"
    fig1.tight_layout()
    fig1.savefig(path1, dpi=180, bbox_inches="tight")
    plt.close(fig1)
    paths.append(path1)

    fig2, ax2 = plt.subplots(figsize=(7.0, 4.6))
    ax2.plot(time_ms, total_force, color="#2a6f97", linewidth=1.8, marker="o", markersize=3.8)
    maybe_log(ax2, total_force)
    ax2.set_xlabel(x_label)
    ax2.set_ylabel("Total force norm [N]")
    ax2.set_title("Gmsh initial mesh: global force residual")
    ax2.grid(alpha=0.28, which="both")
    path2 = fig_dir / "equilibrium_total_force_vs_t.png"
    fig2.tight_layout()
    fig2.savefig(path2, dpi=180, bbox_inches="tight")
    plt.close(fig2)
    paths.append(path2)

    fig3, ax3 = plt.subplots(figsize=(7.0, 4.6))
    ax3.plot(time_ms, max_free_speed, color="#6a4c93", linewidth=1.8, marker="o", markersize=3.8)
    maybe_log(ax3, max_free_speed)
    ax3.set_xlabel(x_label)
    ax3.set_ylabel("Max free speed [m/s]")
    ax3.set_title("Gmsh initial mesh: speed residual")
    ax3.grid(alpha=0.28, which="both")
    path3 = fig_dir / "equilibrium_max_free_speed_vs_t.png"
    fig3.tight_layout()
    fig3.savefig(path3, dpi=180, bbox_inches="tight")
    plt.close(fig3)
    paths.append(path3)

    fig4, axes = plt.subplots(3, 1, figsize=(7.2, 8.4), sharex=True)
    axes[0].plot(time_ms, max_free_force, color="#bc4749", linewidth=1.8, marker="o", markersize=3.2)
    maybe_log(axes[0], max_free_force)
    axes[0].set_ylabel("Max free-force [N]")
    axes[0].set_title("Gmsh initial mesh residuals")
    axes[0].grid(alpha=0.28, which="both")

    axes[1].plot(time_ms, total_force, color="#2a6f97", linewidth=1.8, marker="o", markersize=3.2)
    maybe_log(axes[1], total_force)
    axes[1].set_ylabel("Total force [N]")
    axes[1].grid(alpha=0.28, which="both")

    axes[2].plot(time_ms, max_free_speed, color="#6a4c93", linewidth=1.8, marker="o", markersize=3.2)
    maybe_log(axes[2], max_free_speed)
    axes[2].set_ylabel("Max free speed [m/s]")
    axes[2].set_xlabel(x_label)
    axes[2].grid(alpha=0.28, which="both")

    path4 = fig_dir / "equilibrium_residuals_vs_t.png"
    fig4.tight_layout()
    fig4.savefig(path4, dpi=180, bbox_inches="tight")
    plt.close(fig4)
    paths.append(path4)

    fig5, (ax5a, ax5b) = plt.subplots(2, 1, figsize=(7.2, 7.6), sharex=True)
    ax5a.plot(time_ms, snapshot_volume_delta_pl, color="#1f7a8c", linewidth=1.8, marker="o", markersize=3.2)
    ax5a.axhline(0.0, color="#9ca3af", linestyle="--", linewidth=1.0)
    ax5a.set_ylabel("Delta volume [pL]")
    ax5a.set_title(f"Gmsh tet volume vs target ({target_volume_ul:.6f} uL)")
    ax5a.grid(alpha=0.28)

    ax5b.plot(time_ms, snapshot_volume_rel_percent, color="#bc4749", linewidth=1.8, marker="o", markersize=3.2)
    ax5b.axhline(0.0, color="#9ca3af", linestyle="--", linewidth=1.0)
    ax5b.set_xlabel(x_label)
    ax5b.set_ylabel("Rel. error [%]")
    ax5b.grid(alpha=0.28)

    path5 = fig_dir / "equilibrium_snapshot_volume_rel_error_vs_t.png"
    fig5.tight_layout()
    fig5.savefig(path5, dpi=180, bbox_inches="tight")
    plt.close(fig5)
    paths.append(path5)

    return [str(path) for path in paths]


def _tet_mesh_volume(points: np.ndarray, tets: np.ndarray) -> float:
    pts = np.asarray(points, dtype=float)
    tet_idx = np.asarray(tets, dtype=int)
    if pts.size == 0 or tet_idx.size == 0:
        return 0.0
    total = 0.0
    for a, b, c_, d in tet_idx:
        total += abs(float(np.dot(pts[a] - pts[d], np.cross(pts[b] - pts[d], pts[c_] - pts[d])) / 6.0))
    return float(total)


def _full_free_surface_from_half(z_half: np.ndarray, r_half: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    z = np.asarray(z_half, dtype=float)
    r = np.asarray(r_half, dtype=float)
    return np.concatenate((-z[:0:-1], z)), np.concatenate((r[:0:-1], r))


def _biased_radii_from_neck(
    *,
    neck_radius: float,
    contact_radius: float,
    n_samples: int,
    ratio: float,
) -> np.ndarray:
    n_samples = max(2, int(n_samples))
    r_neck = float(np.clip(neck_radius, 1.0e-8 * contact_radius, 0.999999 * contact_radius))
    if abs(float(ratio) - 1.0) <= 1.0e-12:
        return np.linspace(r_neck, float(contact_radius), n_samples, dtype=float)

    n_gaps = n_samples - 1
    weights = float(ratio) ** np.arange(n_gaps - 1, -1, -1, dtype=float)
    gaps = (float(contact_radius) - r_neck) * weights / float(np.sum(weights))
    radii = np.concatenate([[r_neck], r_neck + np.cumsum(gaps)])
    radii[-1] = float(contact_radius)
    return radii


def _resample_half_profile_to_ratio(
    c: Case2bGmshConfig,
    z_half: np.ndarray,
    r_half: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    z = np.asarray(z_half, dtype=float).copy()
    r = np.asarray(r_half, dtype=float).copy()
    z_cl = _contact_plane_half_gap(c)
    r_cl = float(c.contact_radius_m)
    n_samples = max(2, int(c.free_surface_half_nodes))

    def rounded_from_neck(neck_radius: float) -> tuple[np.ndarray, np.ndarray]:
        z_samples = np.linspace(0.0, z_cl, n_samples, dtype=float)
        u = z_samples / max(z_cl, 1.0e-30)
        rounded_cap = 3.0 * u * u - 2.0 * u * u * u
        r0 = float(np.clip(neck_radius, 1.0e-8 * r_cl, 0.999999 * r_cl))
        r_samples = r0 + (r_cl - r0) * rounded_cap
        z_samples[0] = 0.0
        z_samples[-1] = z_cl
        r_samples[0] = r0
        r_samples[-1] = r_cl
        return z_samples, r_samples

    if z.size < 2 or r.size < 2:
        return rounded_from_neck(0.5 * r_cl)

    finite = np.isfinite(z) & np.isfinite(r)
    z = z[finite]
    r = r[finite]
    if z.size < 2:
        return rounded_from_neck(0.5 * r_cl)

    z[0] = 0.0
    z[-1] = z_cl
    r = np.clip(r, 1.0e-8 * r_cl, r_cl)
    r[-1] = r_cl

    order = np.argsort(r)
    r_sorted = r[order]
    z_sorted = np.clip(z[order], 0.0, z_cl)
    keep_r: list[float] = []
    keep_z: list[float] = []
    for rv, zv in zip(r_sorted, z_sorted):
        rv = float(rv)
        zv = float(zv)
        if keep_r and abs(rv - keep_r[-1]) <= 1.0e-14:
            keep_z[-1] = max(keep_z[-1], zv)
        else:
            keep_r.append(rv)
            keep_z.append(zv)

    r_unique = np.asarray(keep_r, dtype=float)
    z_unique = np.maximum.accumulate(np.asarray(keep_z, dtype=float))
    if r_unique.size < 2:
        return rounded_from_neck(float(r[0]))

    return rounded_from_neck(float(r_unique[0]))


def _scale_half_profile_from_contact(
    c: Case2bGmshConfig,
    z_half: np.ndarray,
    r_half: np.ndarray,
    scale: float,
) -> tuple[np.ndarray, np.ndarray]:
    z = np.asarray(z_half, dtype=float).copy()
    r = np.asarray(r_half, dtype=float).copy()
    r_cl = float(c.contact_radius_m)
    gap = np.maximum(r_cl - r, 0.0)
    r_scaled = r_cl - float(scale) * gap
    r_scaled = np.clip(r_scaled, 1.0e-8 * r_cl, r_cl)
    r_scaled[-1] = r_cl
    return z, r_scaled


def _project_half_profile_to_target_volume(
    c: Case2bGmshConfig,
    z_half: np.ndarray,
    r_half: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    z = np.asarray(z_half, dtype=float).copy()
    r = np.asarray(r_half, dtype=float).copy()
    target = float(c.bridge_volume_m3)
    r_cl = float(c.contact_radius_m)
    max_gap = float(np.max(np.maximum(r_cl - r, 0.0))) if r.size else 0.0
    if max_gap <= 1.0e-30:
        return z, r

    def volume_at(scale: float) -> float:
        z_trial, r_trial = _scale_half_profile_from_contact(c, z, r, scale)
        return _volume_from_meridian_polygon(_make_meridian_polygon_from_half(c, z_trial, r_trial))

    hi = min(20.0, 0.999999 * r_cl / max_gap)
    vol_lo = volume_at(0.0)
    vol_hi = volume_at(hi)
    if target >= vol_lo:
        return _scale_half_profile_from_contact(c, z, r, 0.0)
    if target <= vol_hi:
        return _scale_half_profile_from_contact(c, z, r, hi)

    lo = 0.0
    for _ in range(56):
        mid = 0.5 * (lo + hi)
        vol_mid = volume_at(mid)
        if vol_mid > target:
            lo = mid
        else:
            hi = mid
    return _scale_half_profile_from_contact(c, z, r, 0.5 * (lo + hi))


def _axisymmetric_profile_force_metrics(
    c: Case2bGmshConfig,
    z_half: np.ndarray,
    r_half: np.ndarray,
) -> dict[str, object]:
    z_full, r_full = _full_free_surface_from_half(z_half, r_half)
    n = int(z_full.size)
    if n < 3:
        zero = np.zeros((n, 2), dtype=float)
        return {
            "pressure_scalar_pa": 0.0,
            "residual_pressure_pa": np.zeros(n, dtype=float),
            "curvature_1_per_m": np.zeros(n, dtype=float),
            "area_m2": np.zeros(n, dtype=float),
            "normal_rz": zero,
            "force_rz_n": zero,
            "max_free_force_norm_n": 0.0,
            "rms_free_force_norm_n": 0.0,
            "net_total_force": np.zeros(3, dtype=float),
            "net_total_force_norm_n": 0.0,
            "z_full": z_full,
            "r_full": r_full,
        }

    dr = np.diff(r_full)
    dz = np.diff(z_full)
    ds_seg = np.maximum(np.sqrt(dr * dr + dz * dz), 1.0e-14)
    s = np.concatenate([[0.0], np.cumsum(ds_seg)])
    edge_order = 2 if n >= 3 else 1
    dr_ds = np.gradient(r_full, s, edge_order=edge_order)
    dz_ds = np.gradient(z_full, s, edge_order=edge_order)
    tangent_norm = np.maximum(np.sqrt(dr_ds * dr_ds + dz_ds * dz_ds), 1.0e-14)
    dr_ds = dr_ds / tangent_norm
    dz_ds = dz_ds / tangent_norm
    psi = np.unwrap(np.arctan2(dz_ds, dr_ds))
    dpsi_ds = np.gradient(psi, s, edge_order=edge_order)
    radius = np.maximum(r_full, 1.0e-12)
    curvature = dpsi_ds + dz_ds / radius

    lumped_ds = np.zeros(n, dtype=float)
    lumped_ds[0] = 0.5 * ds_seg[0]
    lumped_ds[-1] = 0.5 * ds_seg[-1]
    if n > 2:
        lumped_ds[1:-1] = 0.5 * (ds_seg[:-1] + ds_seg[1:])
    area = 2.0 * math.pi * radius * lumped_ds

    normal = np.column_stack([dz_ds, -dr_ds])
    normal_norm = np.maximum(np.linalg.norm(normal, axis=1), 1.0e-14)
    normal = normal / normal_norm[:, None]

    free_mask = np.zeros(n, dtype=bool)
    free_mask[1:-1] = True
    weights = np.where(free_mask, area, 0.0)
    pressure_terms = float(c.gamma_n_per_m) * curvature + float(c.rho_kg_per_m3) * float(c.gravity_mps2) * z_full
    if float(np.sum(weights)) > 0.0:
        pressure_scalar = float(np.sum(weights * pressure_terms) / np.sum(weights))
    else:
        pressure_scalar = 0.0
    residual_pressure = float(c.gamma_n_per_m) * curvature - (
        pressure_scalar - float(c.rho_kg_per_m3) * float(c.gravity_mps2) * z_full
    )
    force_rz = residual_pressure[:, None] * area[:, None] * normal
    force_norms = np.linalg.norm(force_rz[free_mask], axis=1) if np.any(free_mask) else np.zeros(0, dtype=float)
    net_z = float(np.sum(force_rz[free_mask, 1])) if np.any(free_mask) else 0.0
    net_total = np.array([0.0, 0.0, net_z], dtype=float)
    return {
        "pressure_scalar_pa": pressure_scalar,
        "residual_pressure_pa": residual_pressure,
        "curvature_1_per_m": curvature,
        "area_m2": area,
        "normal_rz": normal,
        "force_rz_n": force_rz,
        "max_free_force_norm_n": float(np.max(force_norms)) if force_norms.size else 0.0,
        "rms_free_force_norm_n": float(np.sqrt(np.mean(force_norms * force_norms))) if force_norms.size else 0.0,
        "net_total_force": net_total,
        "net_total_force_norm_n": float(np.linalg.norm(net_total)),
        "z_full": z_full,
        "r_full": r_full,
    }


def _half_profile_from_full_relaxed(
    c: Case2bGmshConfig,
    z_full: np.ndarray,
    r_full: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    z_full = np.asarray(z_full, dtype=float)
    r_full = np.asarray(r_full, dtype=float)
    n_half = (int(z_full.size) + 1) // 2
    neck_idx = n_half - 1
    z_half = np.zeros(n_half, dtype=float)
    r_half = np.zeros(n_half, dtype=float)
    z_half[0] = 0.0
    r_half[0] = float(r_full[neck_idx])
    for idx in range(1, n_half):
        bottom = neck_idx - idx
        top = neck_idx + idx
        z_half[idx] = 0.5 * (float(z_full[top]) - float(z_full[bottom]))
        r_half[idx] = 0.5 * (float(r_full[top]) + float(r_full[bottom]))
    z_half[-1] = _contact_plane_half_gap(c)
    r_half[-1] = float(c.contact_radius_m)
    z_half = np.maximum.accumulate(np.clip(z_half, 0.0, _contact_plane_half_gap(c)))
    r_half = np.clip(r_half, 1.0e-8 * float(c.contact_radius_m), float(c.contact_radius_m))
    return _resample_half_profile_to_ratio(c, z_half, r_half)


def _relaxed_half_profile_trial(
    c: Case2bGmshConfig,
    z_half: np.ndarray,
    r_half: np.ndarray,
    metrics: dict[str, object],
    *,
    dt: float,
    sign: float,
) -> tuple[np.ndarray, np.ndarray, float]:
    z_full = np.asarray(metrics["z_full"], dtype=float).copy()
    r_full = np.asarray(metrics["r_full"], dtype=float).copy()
    residual_pressure = np.asarray(metrics["residual_pressure_pa"], dtype=float)
    normal = np.asarray(metrics["normal_rz"], dtype=float)
    damping = max(float(c.relax_damping), 1.0e-12)
    velocity_rz = float(sign) * residual_pressure[:, None] * normal / damping
    velocity_rz[0, :] = 0.0
    velocity_rz[-1, :] = 0.0

    dr = np.diff(r_full)
    dz = np.diff(z_full)
    min_ds = float(np.min(np.sqrt(dr * dr + dz * dz))) if dr.size else 0.0
    max_step = max(float(c.max_step_fraction) * min_ds, 1.0e-9 * float(c.contact_radius_m))
    displacement = float(dt) * velocity_rz
    disp_norm = np.linalg.norm(displacement, axis=1)
    max_disp = float(np.max(disp_norm)) if disp_norm.size else 0.0
    if max_disp > max_step:
        displacement *= max_step / max(max_disp, 1.0e-30)

    r_full[1:-1] += displacement[1:-1, 0]
    z_full[1:-1] += displacement[1:-1, 1]
    z_full[0] = -_contact_plane_half_gap(c)
    z_full[-1] = _contact_plane_half_gap(c)
    r_full[0] = float(c.contact_radius_m)
    r_full[-1] = float(c.contact_radius_m)
    max_speed = float(np.max(np.linalg.norm(displacement, axis=1)) / max(float(dt), 1.0e-30))

    z_trial, r_trial = _half_profile_from_full_relaxed(c, z_full, r_full)
    z_trial, r_trial = _project_half_profile_to_target_volume(c, z_trial, r_trial)
    z_trial, r_trial = _resample_half_profile_to_ratio(c, z_trial, r_trial)
    return z_trial, r_trial, max_speed


def _history_row_from_generation(
    c: Case2bGmshConfig,
    generation: dict[str, object],
    metrics: dict[str, object],
    *,
    step: int,
    time_s: float,
    max_speed_mps: float,
) -> dict[str, object]:
    points = np.asarray(generation["points"], dtype=float)
    tets = np.asarray(generation["tets"], dtype=int)
    mesh_volume_m3 = _tet_mesh_volume(points, tets)
    rel_error = (mesh_volume_m3 - float(c.bridge_volume_m3)) / max(float(c.bridge_volume_m3), 1.0e-30)
    net_total = np.asarray(metrics["net_total_force"], dtype=float)
    return {
        "step": int(step),
        "time_s": float(time_s),
        "pressure_scalar_pa": float(metrics["pressure_scalar_pa"]),
        "snapshot_msh_volume_m3": float(mesh_volume_m3),
        "snapshot_msh_volume_ul": float(1.0e9 * mesh_volume_m3),
        "snapshot_msh_volume_rel_error": float(rel_error),
        "snapshot_msh_volume_rel_error_percent": float(100.0 * rel_error),
        "water_volume_m3": float(mesh_volume_m3),
        "water_volume_ul": float(1.0e9 * mesh_volume_m3),
        "water_volume_rel_error": float(rel_error),
        "water_volume_rel_error_percent": float(100.0 * rel_error),
        "meridian_pappus_volume_m3": float(generation["meridian_volume"]),
        "max_free_force_norm_n": float(metrics["max_free_force_norm_n"]),
        "rms_free_force_norm_n": float(metrics["rms_free_force_norm_n"]),
        "max_free_speed_mps": float(max_speed_mps),
        "net_total_force": net_total.tolist(),
        "net_total_force_norm_n": float(metrics["net_total_force_norm_n"]),
        "free_total_force": net_total.tolist(),
        "sphere_total_force": [0.0, 0.0, 0.0],
        "node_count": int(len(np.asarray(generation["node_tags"], dtype=np.int64))),
        "tet_count": int(len(tets)),
    }


def _advance_reported_free_velocity(
    c: Case2bGmshConfig,
    metrics: dict[str, object],
    velocity_rz: np.ndarray,
    *,
    dt: float,
) -> tuple[np.ndarray, float]:
    force_rz = np.asarray(metrics["force_rz_n"], dtype=float)
    if velocity_rz.shape != force_rz.shape:
        velocity_rz = np.zeros_like(force_rz)
    if force_rz.size == 0:
        return velocity_rz, 0.0

    velocity_next = np.asarray(velocity_rz, dtype=float).copy()
    free_mask = np.zeros(force_rz.shape[0], dtype=bool)
    free_mask[1:-1] = True
    if not np.any(free_mask):
        return velocity_next, 0.0

    n_free = max(int(np.count_nonzero(free_mask)), 1)
    nodal_mass = max(float(c.rho_kg_per_m3) * float(c.bridge_volume_m3) / float(n_free), 1.0e-12)
    damping = max(float(c.relax_damping), 0.0)
    accel = (force_rz - damping * velocity_next) / nodal_mass
    accel[~free_mask, :] = 0.0
    accel_norm = np.linalg.norm(accel, axis=1)
    max_accel = max(float(c.max_acceleration_mps2), 0.0)
    if max_accel > 0.0:
        over = accel_norm > max_accel
        accel[over, :] *= max_accel / np.maximum(accel_norm[over, None], 1.0e-30)

    velocity_next += float(dt) * accel
    velocity_next[~free_mask, :] = 0.0
    speed = np.linalg.norm(velocity_next[free_mask], axis=1)
    return velocity_next, float(np.max(speed)) if speed.size else 0.0


def _axisymmetric_mesh_diagnostics(points: np.ndarray) -> dict[str, int | float]:
    pts = np.asarray(points, dtype=float)
    if pts.size == 0:
        return {"unique_nonaxis_angles": 0, "max_angle_step_error_rad": 0.0}
    radii = np.linalg.norm(pts[:, :2], axis=1)
    mask = radii > 1.0e-12
    if not np.any(mask):
        return {"unique_nonaxis_angles": 0, "max_angle_step_error_rad": 0.0}
    angles = np.mod(np.arctan2(pts[mask, 1], pts[mask, 0]), 2.0 * math.pi)
    angles[np.isclose(angles, 2.0 * math.pi, atol=1.0e-10, rtol=0.0)] = 0.0
    unique = np.unique(np.round(angles, decimals=10))
    if unique.size <= 1:
        return {"unique_nonaxis_angles": int(unique.size), "max_angle_step_error_rad": 0.0}
    ordered = np.sort(unique)
    gaps = np.diff(np.concatenate([ordered, [ordered[0] + 2.0 * math.pi]]))
    target = 2.0 * math.pi / float(unique.size)
    return {
        "unique_nonaxis_angles": int(unique.size),
        "max_angle_step_error_rad": float(np.max(np.abs(gaps - target))),
    }


def _generate_gmsh_geometry_and_mesh_from_profile(
    gmsh,
    c: Case2bGmshConfig,
    *,
    z_half: np.ndarray,
    r_half: np.ndarray,
    profile_source: str,
    brep_path: Path | None,
    step_path: Path | None,
    geo_path: Path | None,
    msh_path: Path | None,
    write_cad: bool,
    terminal: int = 0,
) -> dict[str, object]:
    z_half = np.asarray(z_half, dtype=float)
    r_half = np.asarray(r_half, dtype=float)
    poly_rz = _make_meridian_polygon_from_half(c, z_half, r_half)
    meridian_volume = _volume_from_meridian_polygon(poly_rz)

    if bool(write_cad):
        # CAD export: keep a true OpenCASCADE solid for BREP/STEP inspection.
        gmsh.initialize()
        try:
            gmsh.option.setNumber("General.Terminal", int(terminal))
            gmsh.model.add(f"{c.name}_cad")

            _point_tags, line_tags = _add_polyline_loop(gmsh, poly_rz, c)
            wire = gmsh.model.occ.addWire(line_tags)
            meridian_surface = gmsh.model.occ.addPlaneSurface([wire])
            gmsh.model.occ.synchronize()
            out = gmsh.model.occ.revolve(
                [(2, meridian_surface)],
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1.0,
                2.0 * math.pi,
            )
            gmsh.model.occ.synchronize()

            cad_volume_tags = [tag for dim, tag in out if dim == 3]
            if not cad_volume_tags:
                raise RuntimeError("Gmsh OCC revolve did not create a volume.")

            gmsh.model.addPhysicalGroup(3, cad_volume_tags, 1)
            gmsh.model.setPhysicalName(3, 1, "liquid_volume")
            if brep_path is not None:
                gmsh.write(str(brep_path))
            if step_path is not None:
                gmsh.write(str(step_path))
        finally:
            gmsh.finalize()

    # Mesh export: use Gmsh rotational extrusion in four quarter-turns.  This
    # creates repeated azimuthal sectors instead of an unstructured 3D fill.
    gmsh.initialize()
    try:
        gmsh.option.setNumber("General.Terminal", int(terminal))
        gmsh.model.add(c.name)

        _point_tags, line_tags = _add_polyline_loop_geo(gmsh, poly_rz, c)
        curve_loop = gmsh.model.geo.addCurveLoop(line_tags)
        meridian_surface = gmsh.model.geo.addPlaneSurface([curve_loop])
        gmsh.model.geo.synchronize()

        azimuthal_sectors = _scaled_azimuthal_sectors(c)
        sectors_per_quarter = max(1, int(round(float(azimuthal_sectors) / 4.0)))
        current_surface = (2, meridian_surface)
        volume_tags: list[int] = []
        for _ in range(4):
            out = gmsh.model.geo.revolve(
                [current_surface],
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1.0,
                0.5 * math.pi,
                numElements=[sectors_per_quarter],
                recombine=True,
            )
            current_surface = out[0]
            volume_tags.extend([tag for dim, tag in out if dim == 3])
        gmsh.model.geo.synchronize()

        if not volume_tags:
            raise RuntimeError("Gmsh rotational sweep did not create volumes.")

        gmsh.model.addPhysicalGroup(3, volume_tags, 1)
        gmsh.model.setPhysicalName(3, 1, "liquid_volume")

        surface_tags = [tag for dim, tag in gmsh.model.getEntities(2)]
        if surface_tags:
            gmsh.model.addPhysicalGroup(2, surface_tags, 10)
            gmsh.model.setPhysicalName(2, 10, "liquid_boundary")

        if geo_path is not None:
            gmsh.write(str(geo_path))

        gmsh.option.setNumber("Mesh.MshFileVersion", 4.1)
        gmsh.option.setNumber("Mesh.Algorithm", 5)
        gmsh.option.setNumber("Mesh.MeshSizeExtendFromBoundary", 1)
        gmsh.option.setNumber("Mesh.MeshSizeFromCurvature", 0)
        gmsh.option.setNumber(
            "Mesh.MeshSizeMin",
            min(_scaled_mesh_lc(c, c.lc_contact_line_m), _scaled_mesh_lc(c, c.lc_liquid_air_m)),
        )
        gmsh.option.setNumber("Mesh.MeshSizeMax", _scaled_mesh_lc(c, c.lc_bulk_m))
        gmsh.option.setNumber("Mesh.Optimize", 0)
        gmsh.option.setNumber("Mesh.OptimizeNetgen", 0)

        gmsh.model.mesh.generate(3)
        if msh_path is not None:
            gmsh.write(str(msh_path))
        points, triangles, tets, node_tags, element_counts = _extract_gmsh_mesh_arrays(gmsh)
    finally:
        gmsh.finalize()

    return {
        "points": points,
        "triangles": triangles,
        "tets": tets,
        "node_tags": node_tags,
        "z_half": z_half,
        "r_half": r_half,
        "profile_source": profile_source,
        "meridian_volume": float(meridian_volume),
        "axisymmetric_mesh": True,
        "azimuthal_sectors": _scaled_azimuthal_sectors(c),
        "volume_tags": volume_tags,
        "element_counts": element_counts,
    }


def _generate_gmsh_geometry_and_mesh(
    gmsh,
    c: Case2bGmshConfig,
    *,
    geometry_volume_target_m3: float,
    brep_path: Path,
    step_path: Path,
    geo_path: Path,
    msh_path: Path,
    write_cad: bool = True,
    terminal: int = 0,
) -> dict[str, object]:
    profile_config = replace(c, bridge_volume_m3=float(geometry_volume_target_m3))
    z_half, r_half, profile_source = _free_surface_samples(profile_config)
    return _generate_gmsh_geometry_and_mesh_from_profile(
        gmsh,
        c,
        z_half=z_half,
        r_half=r_half,
        profile_source=profile_source,
        brep_path=brep_path,
        step_path=step_path,
        geo_path=geo_path,
        msh_path=msh_path,
        write_cad=write_cad,
        terminal=terminal,
    )


def build_gmsh_initial_shape(c: Case2bGmshConfig = Case2bGmshConfig()) -> dict[str, object]:
    try:
        import gmsh
    except ImportError as exc:
        raise SystemExit("Install gmsh first: pip install gmsh") from exc

    script_dir = Path(__file__).resolve().parent
    out_dir = script_dir / c.out_dir
    fig_dir = out_dir / "fig"
    out_dir.mkdir(parents=True, exist_ok=True)
    fig_dir.mkdir(parents=True, exist_ok=True)

    brep_path = None
    step_path = None
    msh_path = fig_dir / f"{c.name}.msh"
    geo_path = None

    def format_volume_status(row: dict[str, object]) -> str:
        return (
            f"target_water_volume={1.0e9 * float(c.bridge_volume_m3):.6f} uL, "
            f"current_water_volume={float(row['snapshot_msh_volume_ul']):.6f} uL, "
            f"water_volume_error={100.0 * float(row['snapshot_msh_volume_rel_error']):+.6f} %"
        )

    def generate_profile_mesh(
        z_profile: np.ndarray,
        r_profile: np.ndarray,
        source: str,
        *,
        write_cad: bool = False,
    ) -> dict[str, object]:
        return _generate_gmsh_geometry_and_mesh_from_profile(
            gmsh,
            c,
            z_half=z_profile,
            r_half=r_profile,
            profile_source=source,
            brep_path=brep_path,
            step_path=step_path,
            geo_path=geo_path,
            msh_path=msh_path,
            write_cad=write_cad,
            terminal=0,
        )

    def correct_profile_to_mesh_volume(
        z_profile: np.ndarray,
        r_profile: np.ndarray,
        source: str,
        *,
        step: int,
        max_passes: int,
        write_cad: bool = False,
    ) -> tuple[np.ndarray, np.ndarray, dict[str, object], list[dict[str, float | int]]]:
        z_base = np.asarray(z_profile, dtype=float).copy()
        r_base = np.asarray(r_profile, dtype=float).copy()
        corrections: list[dict[str, float | int]] = []
        rel_tol = max(0.0, float(c.mesh_volume_correction_rel_tol))
        n_passes = max(1, int(max_passes))
        target = float(c.bridge_volume_m3)
        eval_count = 0
        best: tuple[float, np.ndarray, np.ndarray, dict[str, object], float, float] | None = None

        def evaluate(scale: float) -> tuple[float, np.ndarray, np.ndarray, dict[str, object], float, float]:
            nonlocal eval_count, best
            z_eval, r_eval = _scale_half_profile_from_contact(c, z_base, r_base, scale)
            z_eval, r_eval = _resample_half_profile_to_ratio(c, z_eval, r_eval)
            generation_local = generate_profile_mesh(z_eval, r_eval, source, write_cad=False)
            mesh_volume = _tet_mesh_volume(
                np.asarray(generation_local["points"], dtype=float),
                np.asarray(generation_local["tets"], dtype=int),
            )
            rel_error = (mesh_volume - target) / max(target, 1.0e-30)
            eval_count += 1
            corrections.append(
                {
                    "step": int(step),
                    "pass": int(eval_count),
                    "profile_scale_from_contact": float(scale),
                    "meridian_volume_m3": float(generation_local["meridian_volume"]),
                    "mesh_volume_m3": float(mesh_volume),
                    "mesh_volume_relative_error": float(rel_error),
                }
            )
            candidate = (abs(rel_error), z_eval, r_eval, generation_local, mesh_volume, rel_error)
            if best is None or candidate[0] < best[0]:
                best = candidate
            return mesh_volume, z_eval, r_eval, generation_local, rel_error, float(scale)

        mesh0, z0, r0, gen0, rel0, scale0 = evaluate(1.0)
        if abs(rel0) <= rel_tol or n_passes <= 1 or mesh0 <= 0.0:
            z_work, r_work, generation_local = z0, r0, gen0
        else:
            low_scale = 1.0
            high_scale = 1.0
            low_volume = mesh0
            high_volume = mesh0

            # Mesh volume decreases as the contact-to-profile radial gap scale
            # increases.  Bracket the target first, then bisect.
            while low_volume < target and eval_count < n_passes:
                low_scale *= 0.95
                low_volume, _zl, _rl, _gl, _rel, _scale = evaluate(low_scale)
            while high_volume > target and eval_count < n_passes:
                high_scale *= 1.05
                high_volume, _zh, _rh, _gh, _rel, _scale = evaluate(high_scale)

            if low_volume < target or high_volume > target:
                z_work, r_work, generation_local = best[1], best[2], best[3]  # type: ignore[index]
            else:
                while eval_count < n_passes:
                    if abs(low_volume - high_volume) > 1.0e-30:
                        mid_scale = high_scale + (target - high_volume) * (
                            low_scale - high_scale
                        ) / (low_volume - high_volume)
                        lo_bound = min(low_scale, high_scale)
                        hi_bound = max(low_scale, high_scale)
                        pad = 0.05 * (hi_bound - lo_bound)
                        mid_scale = float(np.clip(mid_scale, lo_bound + pad, hi_bound - pad))
                    else:
                        mid_scale = 0.5 * (low_scale + high_scale)
                    mid_volume, z_mid, r_mid, gen_mid, rel_mid, _scale = evaluate(mid_scale)
                    if abs(rel_mid) <= rel_tol:
                        low_scale = high_scale = mid_scale
                        break
                    if mid_volume > target:
                        low_scale = mid_scale
                        low_volume = mid_volume
                    else:
                        high_scale = mid_scale
                        high_volume = mid_volume
                z_work, r_work, generation_local = best[1], best[2], best[3]  # type: ignore[index]

        if write_cad:
            generation_local = generate_profile_mesh(z_work, r_work, source, write_cad=True)
            mesh_volume = _tet_mesh_volume(
                np.asarray(generation_local["points"], dtype=float),
                np.asarray(generation_local["tets"], dtype=int),
            )
            rel_error = (mesh_volume - target) / max(target, 1.0e-30)
            if not corrections or abs(float(corrections[-1]["mesh_volume_relative_error"]) - rel_error) > 1.0e-18:
                corrections.append(
                    {
                        "step": int(step),
                        "pass": int(len(corrections) + 1),
                        "profile_scale_from_contact": None,
                        "meridian_volume_m3": float(generation_local["meridian_volume"]),
                        "mesh_volume_m3": float(mesh_volume),
                        "mesh_volume_relative_error": float(rel_error),
                    }
                )
        return z_work, r_work, generation_local, corrections

    profile_source = "axisymmetric_force_relaxed"
    z_half, r_half, initial_profile_source = _free_surface_samples(c)
    z_half, r_half = _project_half_profile_to_target_volume(c, z_half, r_half)
    z_half, r_half = _resample_half_profile_to_ratio(c, z_half, r_half)

    correction_history: list[dict[str, float | int]] = []
    z_half, r_half, generation, corrections = correct_profile_to_mesh_volume(
        z_half,
        r_half,
        profile_source,
        step=0,
        max_passes=max(1, int(c.mesh_volume_correction_max_passes)),
    )
    correction_history.extend(corrections)

    metrics = _axisymmetric_profile_force_metrics(c, z_half, r_half)
    history: list[dict[str, object]] = [
        _history_row_from_generation(c, generation, metrics, step=0, time_s=0.0, max_speed_mps=0.0)
    ]
    row0 = history[-1]
    print(
        "[initial guess] "
        f"max_free_force={float(row0['max_free_force_norm_n']):.6e} N, "
        f"net_total={float(row0['net_total_force_norm_n']):.6e} N, "
        f"{format_volume_status(row0)}",
        flush=True,
    )
    print(
        f"[equilibrium] step 0/{int(c.total_iterations)}: "
        f"step_wall=0.000000 s, elapsed=0.000000 s, "
        f"max_free_force={float(row0['max_free_force_norm_n']):.6e} N, "
        f"net_total={float(row0['net_total_force_norm_n']):.6e} N, "
        f"max_free_speed={float(row0['max_free_speed_mps']):.6e} m/s, "
        f"{format_volume_status(row0)}",
        flush=True,
    )

    points = np.asarray(generation["points"], dtype=float)
    triangles = np.asarray(generation["triangles"], dtype=int)
    tets = np.asarray(generation["tets"], dtype=int)
    node_tags = np.asarray(generation["node_tags"], dtype=np.int64)
    initial_guess_artifacts = _write_snapshot_artifacts(
        points=points,
        triangles=triangles,
        tets=tets,
        node_tags=node_tags,
        out_base=fig_dir / "mesh_initial_guess",
        title="Case 2b axisym Gmsh: raw initial guess",
        c=c,
        z_half=np.asarray(generation["z_half"], dtype=float),
        r_half=np.asarray(generation["r_half"], dtype=float),
        elev=float(c.interactive_elev_deg),
        azim=float(c.interactive_azim_deg),
    )

    import time

    run_wall_start = time.perf_counter()
    sim_time_s = 0.0
    working_dt = float(c.relax_dt_s)
    max_steps = max(0, int(c.total_iterations))
    reported_velocity_rz = np.zeros_like(np.asarray(metrics["force_rz_n"], dtype=float))
    for step in range(1, max_steps + 1):
        step_wall_start = time.perf_counter()
        base_metrics = _axisymmetric_profile_force_metrics(c, z_half, r_half)
        base_force = float(base_metrics["max_free_force_norm_n"])
        dt_step = working_dt
        accepted: tuple[np.ndarray, np.ndarray, dict[str, object], float] | None = None
        for attempt in range(max(1, int(c.step_max_retries)) + 1):
            candidates: list[tuple[float, np.ndarray, np.ndarray, dict[str, object], float]] = []
            for sign in (1.0, -1.0):
                z_trial, r_trial, speed_trial = _relaxed_half_profile_trial(
                    c,
                    z_half,
                    r_half,
                    base_metrics,
                    dt=dt_step,
                    sign=sign,
                )
                trial_metrics = _axisymmetric_profile_force_metrics(c, z_trial, r_trial)
                candidates.append(
                    (
                        float(trial_metrics["max_free_force_norm_n"]),
                        z_trial,
                        r_trial,
                        trial_metrics,
                        speed_trial,
                    )
                )
            candidates.sort(key=lambda item: item[0])
            best_force, best_z, best_r, best_metrics, best_speed = candidates[0]
            if best_force <= 1.05 * max(base_force, 1.0e-30) or attempt >= int(c.step_max_retries):
                accepted = (best_z, best_r, best_metrics, best_speed)
                break
            dt_step *= float(c.step_retry_dt_scale)
            print(
                f"[equilibrium] step {step}/{max_steps}: retry {attempt + 1} with dt={dt_step:.3e} s",
                flush=True,
            )

        if accepted is None:
            raise RuntimeError(f"axisymmetric force relaxation failed at step {step}")

        reported_velocity_rz, max_speed = _advance_reported_free_velocity(
            c,
            base_metrics,
            reported_velocity_rz,
            dt=dt_step,
        )
        z_half, r_half, metrics, _profile_update_speed = accepted
        z_half, r_half = _project_half_profile_to_target_volume(c, z_half, r_half)
        z_half, r_half = _resample_half_profile_to_ratio(c, z_half, r_half)
        z_half, r_half, generation, corrections = correct_profile_to_mesh_volume(
            z_half,
            r_half,
            profile_source,
            step=step,
            max_passes=max(1, int(c.mesh_volume_correction_max_passes)),
        )
        correction_history.extend(corrections)
        metrics = _axisymmetric_profile_force_metrics(c, z_half, r_half)
        working_dt = dt_step
        sim_time_s += dt_step
        row = _history_row_from_generation(
            c,
            generation,
            metrics,
            step=step,
            time_s=sim_time_s,
            max_speed_mps=max_speed,
        )
        history.append(row)
        step_wall = time.perf_counter() - step_wall_start
        elapsed = time.perf_counter() - run_wall_start
        print(
            f"[equilibrium] step {step}/{max_steps}: "
            f"step_wall={step_wall:.6f} s, elapsed={elapsed:.6f} s, "
            f"dt={dt_step:.3e} s, "
            f"max_free_force={float(row['max_free_force_norm_n']):.6e} N, "
            f"net_total={float(row['net_total_force_norm_n']):.6e} N, "
            f"max_free_speed={float(row['max_free_speed_mps']):.6e} m/s, "
            f"{format_volume_status(row)}",
            flush=True,
        )

    z_half, r_half, generation, corrections = correct_profile_to_mesh_volume(
        z_half,
        r_half,
        profile_source,
        step=max_steps,
        max_passes=max(1, int(c.mesh_volume_correction_max_passes)),
        write_cad=True,
    )
    correction_history.extend(corrections)
    metrics = _axisymmetric_profile_force_metrics(c, z_half, r_half)
    final_row = _history_row_from_generation(
        c,
        generation,
        metrics,
        step=max_steps,
        time_s=sim_time_s,
        max_speed_mps=0.0,
    )
    if history:
        history[-1] = final_row
    else:
        history.append(final_row)
    print(
        f"[equilibrium] final correction: "
        f"elapsed={time.perf_counter() - run_wall_start:.6f} s, "
        f"max_free_force={float(final_row['max_free_force_norm_n']):.6e} N, "
        f"net_total={float(final_row['net_total_force_norm_n']):.6e} N, "
        f"max_free_speed={float(final_row['max_free_speed_mps']):.6e} m/s, "
        f"{format_volume_status(final_row)}",
        flush=True,
    )

    points = np.asarray(generation["points"], dtype=float)
    triangles = np.asarray(generation["triangles"], dtype=int)
    tets = np.asarray(generation["tets"], dtype=int)
    node_tags = np.asarray(generation["node_tags"], dtype=np.int64)
    z_half = np.asarray(generation["z_half"], dtype=float)
    r_half = np.asarray(generation["r_half"], dtype=float)
    meridian_volume = float(generation["meridian_volume"])
    mesh_volume_m3 = _tet_mesh_volume(points, tets)
    element_counts = dict(generation.get("element_counts", {}))
    axisymmetric_mesh = bool(generation.get("axisymmetric_mesh", False))
    azimuthal_sectors = int(generation.get("azimuthal_sectors", 0))
    axisymmetry_diagnostics = _axisymmetric_mesh_diagnostics(points)
    tet_count = int(len(tets))
    node_count = int(len(node_tags))
    initial_artifacts = _write_snapshot_artifacts(
        points=points,
        triangles=triangles,
        tets=tets,
        node_tags=node_tags,
        out_base=fig_dir / "mesh_initial",
        title="Case 2b axisym Gmsh: relaxed initial mesh",
        c=c,
        z_half=z_half,
        r_half=r_half,
        elev=float(c.interactive_elev_deg),
        azim=float(c.interactive_azim_deg),
    )
    iter_artifacts = _write_snapshot_artifacts(
        points=points,
        triangles=triangles,
        tets=tets,
        node_tags=node_tags,
        out_base=fig_dir / f"mesh_iter{int(c.total_iterations):04d}",
        title=f"Case 2b axisym Gmsh: mesh iter {int(c.total_iterations):04d}",
        c=c,
        z_half=z_half,
        r_half=r_half,
        elev=float(c.interactive_elev_deg),
        azim=float(c.interactive_azim_deg),
    )

    radial_gaps = np.diff(r_half)
    cl_gap_ratio = float(radial_gaps[-2] / radial_gaps[-1]) if radial_gaps.size >= 2 else float("nan")
    history_fig_paths = _render_equilibrium_history_figures(history, fig_dir)
    summary = {
        "config": asdict(c),
        "initial_profile_source": initial_profile_source,
        "profile_source": profile_source,
        "snapshots": {
            "mesh_initial_guess": initial_guess_artifacts,
            "mesh_initial": initial_artifacts,
            f"mesh_iter{int(c.total_iterations):04d}": iter_artifacts,
        },
        "history_figures": history_fig_paths,
        "msh": str(msh_path),
        "mesh_volume_correction_history": correction_history,
        "mesh_density_factor": _mesh_density_factor(c),
        "scaled_mesh_sizes_m": {
            "lc_contact_line_m": _scaled_mesh_lc(c, c.lc_contact_line_m),
            "lc_liquid_air_m": _scaled_mesh_lc(c, c.lc_liquid_air_m),
            "lc_cap_m": _scaled_mesh_lc(c, c.lc_cap_m),
            "lc_bulk_m": _scaled_mesh_lc(c, c.lc_bulk_m),
        },
        "axisymmetric_mesh": axisymmetric_mesh,
        "azimuthal_sectors": azimuthal_sectors,
        "axisymmetry_diagnostics": axisymmetry_diagnostics,
        "msh_element_counts": element_counts,
        "contact_plane_gap_m": 2.0 * _contact_plane_half_gap(c),
        "surface_gap_m": c.initial_d_over_r * c.particle_radius_m,
        "bottom_sphere_center_z_m": _sphere_center_z(c, top=False),
        "top_sphere_center_z_m": _sphere_center_z(c, top=True),
        "target_volume_m3": c.bridge_volume_m3,
        "meridian_pappus_volume_m3": meridian_volume,
        "volume_relative_error": (meridian_volume - c.bridge_volume_m3) / c.bridge_volume_m3,
        "volume_relative_error_percent": 100.0 * (meridian_volume - c.bridge_volume_m3) / c.bridge_volume_m3,
        "mesh_volume_m3": mesh_volume_m3,
        "mesh_volume_ul": 1.0e9 * mesh_volume_m3,
        "mesh_volume_relative_error": (mesh_volume_m3 - c.bridge_volume_m3) / c.bridge_volume_m3,
        "mesh_volume_relative_error_percent": 100.0 * (mesh_volume_m3 - c.bridge_volume_m3) / c.bridge_volume_m3,
        "final_pressure_scalar_pa": float(metrics["pressure_scalar_pa"]),
        "final_max_free_force_norm_n": float(final_row["max_free_force_norm_n"]),
        "final_total_force_norm_n": float(final_row["net_total_force_norm_n"]),
        "final_max_free_speed_mps": float(final_row["max_free_speed_mps"]),
        "free_surface_half_r_m": r_half.tolist(),
        "free_surface_half_z_m": z_half.tolist(),
        "contact_line_adjacent_radial_gap_ratio": cl_gap_ratio,
        "node_count": node_count,
        "decomposed_tet_count_for_csv": tet_count,
        "tet_count": tet_count,
    }

    print("=" * 72)
    print("Case 2b axisymmetric initial shape generated with Gmsh")
    print("=" * 72)
    print(f"Fig dir                   = {fig_dir}")
    if history_fig_paths:
        print("History PNGs              =")
        for path in history_fig_paths:
            print(f"  {path}")
    print(f"Profile source            = {profile_source}")
    print(f"Target volume             = {1.0e9 * c.bridge_volume_m3:.6f} uL")
    print(f"Pappus volume estimate    = {1.0e9 * meridian_volume:.6f} uL")
    print(f"Mesh volume estimate      = {1.0e9 * mesh_volume_m3:.6f} uL")
    print(f"CL radial gap ratio       = {cl_gap_ratio:.6f}")
    print(f"Mesh density factor       = {_mesh_density_factor(c):.6f}")
    print(f"Relax dt                  = {float(c.relax_dt_s):.3e} s")
    print(f"Total iterations          = {int(c.total_iterations)}")
    print(f"Final pressure scalar     = {float(metrics['pressure_scalar_pa']):.12e} Pa")
    print(f"Final max free-force norm = {float(final_row['max_free_force_norm_n']):.12e} N")
    print(f"Final total-force norm    = {float(final_row['net_total_force_norm_n']):.12e} N")
    print(f"Final max free speed      = {float(final_row['max_free_speed_mps']):.12e} m/s")
    print(f"Axisymmetric mesh         = {axisymmetric_mesh}")
    print(f"Azimuthal sectors         = {azimuthal_sectors}")
    print(f"MSH element counts        = {element_counts}")
    print(f"Nodes / decomposed tets   = {node_count} / {tet_count}")
    if bool(c.open_interactive_window):
        print(f"Opening interactive full mesh = step {int(c.interactive_step)}")
        display_points, display_triangles = _remove_midplane_surface_ring(
            points,
            triangles,
            r_neck=float(r_half[0]),
        )
        _show_interactive_mesh(
            display_points,
            display_triangles,
            title=f"Case 2b axisym Gmsh: full mesh step {int(c.interactive_step):04d}",
            elev=float(c.interactive_elev_deg),
            azim=float(c.interactive_azim_deg),
        )
    return summary


def main() -> None:
    build_gmsh_initial_shape()


if __name__ == "__main__":
    main()
